### ISSUE TITLE
semver test case failed

### ISSUE THREAD

**Issue by ruleeeer** [originjs/vite-plugin-federation#115]
@zgid123 I submitted a pr to add a build to semver, but there seems to be a problem with some of the unit tests, I skipped both test cases for now, can you re-initiate a pr to fix this and turn on the tests?
![image](https://user-images.githubusercontent.com/70385062/145332697-7126563f-1a84-4d9c-a45e-845b7a143caa.png)

**Comment by zgid123** [comment]
sure. I really don't know why, if I run them alone, it will pass 😂

**Comment by zgid123** [comment]
I have an idea, we can make semver as a project of monorepo, and let rollup to compile the code for `vite-plugin-federation`. What do you think?

**Comment by ruleeeer** [comment]
What you said I probably already did, but instead of using monorepo, I used mutli input rollup, you can check this PR(#114 )

**Comment by zgid123** [comment]
oh nice. Sorry, just not enough of coffee. Lemme fix the test cases again. The semver will not work for pre-release version now due to lack of test case, so I skipped that. I will add that part when I have a test case or my project uses a package with pre-release version
