### ISSUE TITLE
vue3 host 与 remote vue 版本冲突的问题

### ISSUE THREAD

**Issue by ybom77** [originjs/vite-plugin-federation#118]
### Versions

- originjs: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
host 与 remote 都设置  shared: ["vue"]

在不引入其他库【例如：组件库】的时候，可以正常工作

但是一旦引入了组件库，或者使用了slot，就会报错如下

Cannot read property 'isCE' of null in remote component with slot using Module Federation

https://github.com/vuejs/vue-next/issues/4344

vite.config.js
``` 
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import federation from '@originjs/vite-plugin-federation'

import Components from 'unplugin-vue-components/vite'
import { PrimeVueResolver } from 'unplugin-vue-components/resolvers'

import path, { join } from 'path'
import { writeFileSync } from 'fs'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    Components({
      resolvers: [
        PrimeVueResolver()
      ]
    }),
    federation({
      name: 'home',
      filename: 'remoteEntry.js',
      exposes: {
        './Content': './src/components/HelloWorld.vue',
        './Container': './src/Container.vue',
        './Button': './src/components/Button.vue'
      },
      shared: ["vue"]
    })
  ],
  build: {
    assetsInlineLimit: 40960,
    target: 'esnext',
    minify: true,
    cssCodeSplit: false,
    rollupOptions: {
      output: {
        minifyInternalExports: false,
      },
    },
  },
})
```

请问应该如何正确配置

**Comment by ruleeeer** [comment]
Could you give me a sandbox or repository to reproduce the problem?
And I checked the associated ISSUE and theoretically unless you configure `requireVersion` to force the required vue version, the remote and host side should be running with the same vue lib.

**Comment by ybom77** [comment]
Thank you for your prompt reply

there is my  demo adress : [github demo](https://github.com/ybom77/demo-vite)

Hope to get your help

**Comment by ruleeeer** [comment]
![image](https://user-images.githubusercontent.com/70385062/149324589-6bf8a93d-8f11-436e-a224-1d3e01d20730.png)
Is the correct result supposed to be like this? I see no error reported by console

**Comment by ybom77** [comment]
~~weird

In my console it is like this

![image](https://user-images.githubusercontent.com/15134783/149327635-6ff0999a-db57-4e4b-9af3-679dfdb4ba1b.png)

how did you do it, can you tell me the steps

**Comment by ruleeeer** [comment]
You can modify the shared content in the `demo-vite/packages/vue3-primevue/vite.config.ts` file as follows
``` ts
shared: ["vue","primevue/button"]
```
Then you will get the result in the above figure.

But there is still the nagging problem that you may need to bring in the contents of primevue peeled shrimp multiple times, depending on how many components of primevue you use, because there is no main field under the primevue root package.json to specify the entry file for the whole package (at least I didn't find one), but rather each folder is a separate package, so there may be such a shared:
``` ts
shared: ["vue","primevue/button","primevue/dialog","primevue/menu",...and so on]
```

**Comment by ruleeeer** [comment]
After I changed the shared content, the result is normal

**Comment by ybom77** [comment]
It's my problem, now it works fine , thanks for your help

**Comment by iotopo** [comment]
@ybom77 你好，我也是因为使用了slot遇到了类似的问题，但没有引用第三方库，您这个问题是怎么解决的？

**Comment by chen1328068199** [comment]
@iotopo 你好，有解决slot的问题吗

**Comment by dlpuzhangyue** [comment]
> @iotopo 你好，有解决slot的问题吗

插眼，同问。解决后麻烦@。

**Comment by godIsAProgrammer** [comment]
解决了吗？朋友们。

**Comment by rasyaddotgg** [comment]
> got this error with `shared: ['vue', 'primevue/button']`
> 
> ```
> main-app/fe build: file:///Volumes/Working/project/micro-app/main-app/fe/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287
> main-app/fe build:         base = Object.assign(new Error(base.message), base);
> main-app/fe build:                              ^
> main-app/fe build: Error [RollupError]: No description file or no version in description file (usually package.json) of primevue/button. Add version to description file, or manually specify version in shared config.
> main-app/fe build:     at error (file:///Volumes/Working/project/micro-app/main-app/fe/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
> main-app/fe build:     at Object.error (file:///Volumes/Working/project/micro-app/main-app/fe/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
> main-app/fe build:     at Object.buildStart (file:///Volumes/Working/project/micro-app/main-app/fe/node_modules/.pnpm/@originjs+vite-plugin-federation@1.3.2/node_modules/@originjs/vite-plugin-federation/dist/index.mjs:756:18) {
> main-app/fe build:   code: 'PLUGIN_ERROR',
> main-app/fe build:   plugin: 'originjs:federation'
> main-app/fe build: }
> main-app/fe build: Node.js v18.7.0
> ```

Same bro. how to fix this issue?
