### ISSUE TITLE
"vue3-advanced-demo" not works well 

### ISSUE THREAD

**Issue by lzr900515** [originjs/vite-plugin-federation#120]
![image](https://user-images.githubusercontent.com/15673574/151531252-4c364d3e-aad1-41a8-9f29-7186e6046c04.png)
element-plus components are not been rendered。 only simple component can work well. if a component contains another one, will not work.
### Versions
- node: v16.13.2
- @originjs/vite-plugin-federatio: ^1.1.0
- vue:  ^3.2.0

another problem happened to me was when i use shared i got a wrong msg like that:

Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
1  |  import {importShared} from './__federation_fn_import.js'
2  |  import { _ as _export_sfc } from './plugin-vue_export-helper.21dcd24c.js';
3  |  const {resolveComponent,openBlock,createElementBlock,createVNode,withCtx,Fragment,createTextVNode} = await importShared('vue')

**Comment by ruleeeer** [comment]
Can you give me a repository or sandbox that can reproduce the problem, reporting errors I may not see the problem？

> Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
This is probably because you ran the project in a browser that doesn't support top-level await syntax or you didn't set `target:'esnext'` in the vite configuration file

**Comment by lzr900515** [comment]
> Can you give me a repository or sandbox that can reproduce the problem, reporting errors I may not see the problem？
> 
> > Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
> 
> This is probably because you ran the project in a browser that doesn't support top-level await syntax or you didn't set `target:'esnext'` in the vite configuration file

ok, i will make a repository . thanks  for ur reply  and happy Chinese New  Year

**Comment by lzr900515** [comment]
> 
hellow，here is the repository . i just used ur demo.  nothing changed . only used nginx to do some proxy.  README tell the repository  step. and a nginx.conf file alse in it.
 
https://github.com/lzr900515/vue3-advanced-demo

**Comment by ruleeeer** [comment]
Thank you for the repository, I will look at the relevant issues when I have time, in addition, Happy New Year (is this time just right, hahaha)

**Comment by lzr900515** [comment]
> 

Haha, you are right for the new year's time. i just finished my holiday and back to work.  :( ...   by the way, is my repository can reproduce the issues?  if have any question, please tell me, i will reply as soon as possible~

**Comment by ruleeeer** [comment]
I checked the repository and verified that I was not familiar with nginx, so I did not use nginx, and I found that it worked fine, of course, I changed the address of remoteEntry.js (because I did not use niginx) to http://localhost:5004/assets/remoteEntry. js, and then run `pnpm build & pnpm serve` in two monoRepo's respectively to get the following result
<img width="443" alt="image" src="https://user-images.githubusercontent.com/70385062/153118683-bb60ea61-f311-4b61-a80c-03d034ccaf1f.png">
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/70385062/153118515-c70d1b00-64f3-48cc-a4ab-9356d6e26edc.png">
Is it because of the configuration of nginx?Or is there some extra work needed when using it with nginx?

**Comment by lzr900515** [comment]
e...you are right. it seems that when i use 'npm run dev' at the host project, it use websocket to keep the hot reload. use nginx may not work for the hot reload. when i use nginx with 'npm run serve' in both host and remote project, it works...  i should find a way to proxy the websocket maybe...

anyway，thanks a lot for your help~
