### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'exports')

### ISSUE THREAD

**Issue by lolocoo** [originjs/vite-plugin-federation#122]
### Versions

- originjs: 1.1.0
- node: 16.13.1

### Reproduction

host vite.config and remote vite.config  as below
...
build: {
  target: 'esnext',
},
...
shared: {
  react: { singleton: true },
  'react-dom': {
    singleton: true,
   },
 },

build remote & npm run preview

host refference remote component, display error info 
```
TypeError: Cannot read properties of undefined (reading 'exports')
```

remove remote shared react-dom， it's works with normal element.
if the component refference other lib for eg. antd Header.
It's cause error with 
```
https://reactjs.org/docs/error-decoder.html?invariant=321 
```

### What is Expected?
add react-dom to shared works and work together with other lib

**Comment by ruleeeer** [comment]
I assume you have other component libraries that use react/react-dom, please add them to shared as well, otherwise it may result in multiple different react/react-dom in the runtime environment

**Comment by lolocoo** [comment]
> I assume you have other component libraries that use react/react-dom, please add them to shared as well, otherwise it may result in multiple different react/react-dom in the runtime environment

I add all of them

```Javascript
  shared: {
      react: { singleton: true },
      'react-dom': {
        singleton: true,
      },
      antd: {
        singleton: true,
      },
    },
```
warning 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'exports')
    at __federation_shared_antd.js:1:438
```
Is this plugin experimental， is it full feature like webpack module federation?

**Comment by ruleeeer** [comment]
This problem seems strange, can you provide me with a link to a repository or sandbox where I can reproduce the problem?

**Comment by lolocoo** [comment]
Here is git respository https://github.com/lolocoo/vite-federation-issue-reproduce.git

**Comment by ruleeeer** [comment]
I found some problems after checking out the repository,when I use dev mode, the console also reports an error
I tried to use build & serve to start the host side and found that it works, I get the following result

<img width="241" alt="image" src="https://user-images.githubusercontent.com/70385062/153140668-7dfb703f-9418-414a-85ba-bfe91bf26f50.png">

If this result is normal, the reason should be that there are some problems with the plugin's support for react in dev mode

**Comment by lolocoo** [comment]
> I found some problems after checking out the repository,when I use dev mode, the console also reports an error I tried to use build & serve to start the host side and found that it works, I get the following result
> 
> <img alt="image" width="241" src="https://user-images.githubusercontent.com/70385062/153140668-7dfb703f-9418-414a-85ba-bfe91bf26f50.png">
> 
> If this result is normal, the reason should be that there are some problems with the plugin's support for react in dev mode

Thank you for your help. Will you solve this problem? I will use it in my project if not will migrate vite to webpack. It's so painfull.

**Comment by ruleeeer** [comment]
I will fix this, but it will take some time and I suggest you use webpack

**Comment by sanyuan0704** [comment]
> ``

Have you  fixed it?I meet the same problem.

**Comment by sanyuan0704** [comment]
> I will fix this, but it will take some time and I suggest you use webpack

Have you fixed it?I meet the same problem.

**Comment by UrielJavier** [comment]
i have the same problem :/

**Comment by chancmg** [comment]
We are facing the same issue.. Can we re-open the issue?

**Comment by yuvalbne** [comment]
@ruleeeer @sanyuan0704 
Someone have an idea about this issue???
