### ISSUE TITLE
there are  warning  about  element-plus in   examples/vue3-advanced-demo

### ISSUE THREAD

**Issue by jzfai** [originjs/vite-plugin-federation#137]
![image](https://user-images.githubusercontent.com/35098590/156524181-2443d5dd-5b8e-4847-9950-8463d33f4cb6.png)

**Comment by ruleeeer** [comment]
It looks like the previous change affected the example, let me fix it

**Comment by ruleeeer** [comment]
thanks , try to pull the project or upgrade `vite-plugin-federation` to version `1.1.2`, the problem should be solved
