### ISSUE TITLE
styles in the dependencies of exposed component are not imported

### ISSUE THREAD

**Issue by Timehello** [originjs/vite-plugin-federation#147]
problem:
1. styles in the dependencies of exposed component are not imported
2. the dependency of exposed component will extra import the shared lib if the denpendency in the single chunk

[reproduce repo](https://github.com/Timehello/federation-test)

### Describe the solution you'd like

- [x] 1. the style of dependencies should be automatically imported

- [x] 2. shared libs should not be imported if the host app provides

### Describe alternatives you've considered

for problem 1, try to add all css chunk of dependencies in generateBundle hook, the param of dynamicLoadingCss method is modified to array type, to support import multiple css chunks
for problem 2, if an app in exposes flag, use the importShared function instead of commonly refer the shared lib

I try to fix these 2 problems, here is a [PR](https://github.com/originjs/vite-plugin-federation/pull/148)

If these is something i miss, please let me know :-)

**Comment by ruleeeer** [comment]
@Timehello Could you fix the CI related first?

**Comment by Timehello** [comment]
> @Timehello Could you fix the CI related first?

ok, i try fix them later

**Comment by Timehello** [comment]
> @Timehello Could you fix the CI related first?

Hi, all problems are solved

**Comment by ruleeeer** [comment]
Can you give me some more detailed description of the second issue?
I see that the exposed component is already using shared
``` js
// __federation_expose_CA.js
import {importShared} from './__federation_fn_import.js'
import {cC} from './c-c.01674645.js';

const {
  openBlock,
  createElementBlock,
  createElementVNode: createBaseVNode,
  createVNode,
  Fragment
} = await importShared('vue')
```

**Comment by Timehello** [comment]
@ruleeeer you can find out the problem in c-c component:
```js
// c-c.2ce29afa.js
import { openBlock, createElementBlock } from './__federation_shared_vue.js'; // import the share lib
```
c-c component import the shared vue that host app has provided

**Comment by ruleeeer** [comment]
@Timehello 
I can accept the css related changes, but shared needs to be modified in a more logical way than just using the shared function for all components

**Comment by Timehello** [comment]
@ruleeeer yes, it should be handled more logically

**Comment by theanha5** [comment]
I'm still struggling with problem 1. Any updates, guys?

**Comment by ruleeeer** [comment]
> I'm still struggling with problem 1. Any updates, guys?

Can you give me a reproduction use case?

**Comment by theanha5** [comment]
@ruleeeer Could you check the [reproduce repo](https://github.com/Timehello/federation-test) of @Timehello . I got the same exactly (setting `cssCodeSplit: true`

**Comment by theanha5** [comment]
I noticed when I set `cssCodeSplit: false`, dynamicCss will be added to `moduleMap` in `remoteEntry.js`
![image](https://user-images.githubusercontent.com/37961082/185029395-c00f0a31-1796-4516-9a5a-2f5d1c00be7f.png)

But when `cssCodeSplit: true`, it's not added

![image](https://user-images.githubusercontent.com/37961082/185029799-c45864fc-955e-4fb3-b861-1588b18256fb.png)

My version: `1.1.8`

**Comment by JokerFrankZ** [comment]
> 
i hava same problem

**Comment by JokerFrankZ** [comment]
> I noticed when I set `cssCodeSplit: false`, dynamicCss will be added to `moduleMap` in `remoteEntry.js` ![image](https://user-images.githubusercontent.com/37961082/185029395-c00f0a31-1796-4516-9a5a-2f5d1c00be7f.png)
> 
> But when `cssCodeSplit: true`, it's not added
> 
> ![image](https://user-images.githubusercontent.com/37961082/185029799-c45864fc-955e-4fb3-b861-1588b18256fb.png)
> 
> My version: `1.1.8`

i hava same problem

**Comment by pganster** [comment]
This is intentionally designed like this, see [this comment](https://github.com/originjs/vite-plugin-federation/blob/084033339d07c0d09cff34ead30a14c0346c9154/packages/lib/src/prod/expose-production.ts#L172). When `cssCodeSplit` is enabled, the plugin assumes that you've handled your css imports yourself in your corresponding components.

The next problem is that when importing a stylesheet in a component like `import 'my-style.scss'`, vite will automatically inject the built css file in the index.html of the app. This of course doesn't help us, as when only using the exposed component of a remote, the index.html is never sourced.

To workaround this problem, one can dynamically import a style at the top of a file like `import('my-style.scss')`, which will then be loaded as soon as this remote component is being rendered.
