### ISSUE TITLE
Transpiling of scoped packages

### ISSUE THREAD

**Issue by BEGEMOT9I** [originjs/vite-plugin-federation#150]
### Versions

- originjs: last
- node: last

### Reproduction

TODO

### Steps to reproduce

1) You need a scoped dep (for example, `@company/ui`)
2) You need to share this package (for example, `shared: ['@company/ui']`)
3) You need to use remote/host bundled by webpack with same shared dep.

### What is Expected?

In webpack and vite shared scope this package must be called as `@company/ui`

### What is actually happening?

In webpack shared scope this package will be as it is - `@company/ui`
In vite shared scope this package **will be formatted** - `@companyUi`

When webpack is a remote and vite is a host, webpack tries to request a package with `@company/ui` name, but in the vite scope it is called differently: `@companyUi`. As i undestand, the problem into this place with [`removeNonLetter`](https://github.com/originjs/vite-plugin-federation/blob/main/packages/lib/src/utils/index.ts#L132) utility, that transpiles imports

**Comment by BEGEMOT9I** [comment]
It seems that removing the utility in these places solves the problem. But I'm not sure if it breaks something. 
https://github.com/originjs/vite-plugin-federation/blob/main/packages/lib/src/prod/remote-production.ts#L189
https://github.com/originjs/vite-plugin-federation/blob/main/packages/lib/src/prod/remote-production.ts#L132

**Comment by ruleeeer** [comment]
Thanks, this is the part that the test case doesn't cover
