### ISSUE TITLE
Issue with shared react dependency

### ISSUE THREAD

**Issue by HeadFox** [originjs/vite-plugin-federation#161]
We have this error when using shared dependencies `react` + `react-dom`:
`Uncaught TypeError: application 'myRemoteApp' died in status LOADING_SOURCE_CODE: Cannot read properties of undefined (reading 'ReactCurrentOwner')`

This error is not happening if we removed shared from the option of the plugin. (But react is loaded two times)

### Versions

- originjs: 1.1.3
- node: 16.14

### Reproduction

We will create a reproduction as soon as possible but maybe we are doing something wrong with our config.
We don't see any exemple that use react on both side.

Config on vite (host)
```typescript
 federation({
      name: 'myApp',
      remotes:{
        myRemoteApp: {
          external: 'http://localhost:3001/remoteEntry.js',
          format: 'var',
        }
      },
      shared: {
        react: {
          version: '^17.0.1',
        },
        'react-dom': {
          version: '^17.0.1',
        }
      }
    }),
```

Config on Webpack (remote)
```javascript
  new ModuleFederationPlugin({
            name: 'myRemoteApp',
            filename: 'remoteEntry.js',
            exposes: {
                './App': './src/App',
            },
            shared: [
                {
                    ...deps,
                    react: {
                        singleton: true,
                        requiredVersion: deps.react,
                    },
                    'react-dom': {
                        singleton: true,
                        requiredVersion: deps['react-dom'],
                    },
                },
            ],
        }),
```

This Webpack configuration for the remote is perfectly working with an other Webpack config as host.

Thank you for your help.
We will try to provide reproduction as soon as possible

**Comment by ruleeeer** [comment]
@HeadFox Could you tell me what mode you used to start it?If you are using dev, please try to start again using host (because react is not ESM yet, which leads to some compatibility issues when packaging)

**Comment by ruleeeer** [comment]
Also, please add the configuration `from:'webpack'` to the remote configuration like this
``` js
remotes:{
        myRemoteApp: {
          external: 'http://localhost:3001/remoteEntry.js',
          from: 'webpack',
          format: 'var',
        }
      },
```

**Comment by HeadFox** [comment]
Hi ! Thanks for your fast reply 🙏 
I tried both and it's not working. Here is a reproduction repo: https://github.com/HeadFox/issue-161-vite-plugin-federation
You will find a working host with webpack as well

**Comment by HeadFox** [comment]
I can confirm it works now 🔥 Thanks a lot @Timehello
