### ISSUE TITLE
preload-helper.js not found

### ISSUE THREAD

**Issue by zhanghaibiao4913** [originjs/vite-plugin-federation#164]
![image](https://user-images.githubusercontent.com/29319580/162110280-fcd07505-64ef-4bf4-aec7-4559e5c74003.png)

"@originjs/vite-plugin-federation": "^1.1.3"
"vite": "^2.8.6"

**Comment by enzi077** [comment]
@zhanghaibiao4913 did you find the solution for this ? what was it ?
