### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'exports')

### ISSUE THREAD

**Issue by philals** [originjs/vite-plugin-federation#173]
Thanks for spending the time to read this issue.

I have read and attempted fixes listed here:
- https://github.com/originjs/vite-plugin-federation/discussions/162
- https://github.com/originjs/vite-plugin-federation/issues/122
- https://github.com/originjs/vite-plugin-federation/issues/161

Both host and remote are Vite projects

### Versions

"@originjs/vite-plugin-federation": "1.1.4",

### Reproduction

Clone this repo https://github.com/philals/reading-exports-issue/

cd into each directory and run `npm install && npm run watch`. This will run the container in dev mode (localhost:3000) and the remote served statically on localhost:3001

Confirm working

**Uncomment this line: https://github.com/philals/reading-exports-issue/blob/master/app/src/App.tsx#L6**

Refresh browser, issue encountered.

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

Above

### What is Expected?

All working

### What is actually happening?
Error: Uncaught TypeError: Cannot read properties of undefined (reading 'exports')

![image](https://user-images.githubusercontent.com/8849355/164305268-cc834665-cca3-413c-89c3-0d853f5302d5.png)

![image](https://user-images.githubusercontent.com/8849355/164305060-bc2e9873-7c68-4623-b020-6eef6e518e6f.png)

**Comment by ruleeeer** [comment]
I recommend using `React.useState` instead of `useState`, or you can continue to use `useState` but need to start the host using build&serve mode (instead of the existing dev)

**Comment by ruleeeer** [comment]
The root cause of this problem is the need to keep the shared product consistent in esbuild (vite dev mode) and rollup (vite build mode), otherwise it will cause problems, esuild and rollup are consistent in the esm library, but unfortunately react is a cjs library, if react switch to esm this problem does not exist, otherwise you can only use some specific usage to circumvent

**Comment by philals** [comment]
Thanks for the heads up @ruleeeer 

Confirmed it has resolved my issue. 

Have pushed a new commit to my demo with fix for anyone else https://github.com/philals/reading-exports-issue/commit/501151290df7d8f04d28c7cc092674c7f53e1201

**Comment by SaiMadhav9494** [comment]
I have two react apps configured with vite and this plugin. I tried building them and served through preview, still not able to get them work together. I am not sure of what is going wrong with sharing my dependencies. I was actually sharing material-ui in the remote component (which failed), so I tried using useState but failed.

link to my repo https://github.com/SaiMadhav9494/vite-micro-frontend

remote app: 
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import federation from '@originjs/vite-plugin-federation'
import {dependencies} from './package.json'

// https://vitejs.dev/config/
export default defineConfig({
  server:{
    host: 'local.ravenslingshot.com',
    port: 5000,
  },
  preview: {
    port: 5000,
  },
  plugins: [
    react(),
    federation({
      name: 'NavBarVite',
      filename: 'remoteEntry.js',
      exposes: {
        './App': './src/App.tsx'
      },
      shared: {
        ...dependencies,
        react: {
          requiredVersion: dependencies['react']
        },
        "react-dom": {
          requiredVersion: dependencies['react-dom']
        }
      }
    })
  ],
  build: {
    target: 'esnext',
    minify: false,
    cssCodeSplit: false
  },
})
```
host app:
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import federation from '@originjs/vite-plugin-federation'
import {dependencies} from './package.json'

// https://vitejs.dev/config/
export default defineConfig({
  server:{
    host: 'local.ravenslingshot.com',
    port: 5001,
  },
  preview: {
    port: 5001
  },
  plugins: [
    react(),
    federation({
      name: 'host-vite',
      remotes: {
        NavBarVite: 'http://local.ravenslingshot.com:5000/assets/remoteEntry.js'
      },
      shared: {
        ...dependencies,
        react: {
          requiredVersion: dependencies['react']
        },
        "react-dom": {
          requiredVersion: dependencies['react-dom']
        }
      }
    })
  ],
  build: {
    target: 'esnext',
    minify: false,
    cssCodeSplit: false
  },
})

```

![image](https://user-images.githubusercontent.com/39062289/191358415-fc437a8a-642e-400a-b1d0-488f9b120455.png)

**Comment by ccreusat** [comment]
> I have two react apps configured with vite and this plugin. I tried building them and served through preview, still not able to get them work together. I am not sure of what is going wrong with sharing my dependencies. I was actually sharing material-ui in the remote component (which failed), so I tried using useState but failed.
> 
> link to my repo https://github.com/SaiMadhav9494/vite-micro-frontend
> 
> remote app:
> 
> ```
> import { defineConfig } from 'vite'
> import react from '@vitejs/plugin-react'
> import federation from '@originjs/vite-plugin-federation'
> import {dependencies} from './package.json'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   server:{
>     host: 'local.ravenslingshot.com',
>     port: 5000,
>   },
>   preview: {
>     port: 5000,
>   },
>   plugins: [
>     react(),
>     federation({
>       name: 'NavBarVite',
>       filename: 'remoteEntry.js',
>       exposes: {
>         './App': './src/App.tsx'
>       },
>       shared: {
>         ...dependencies,
>         react: {
>           requiredVersion: dependencies['react']
>         },
>         "react-dom": {
>           requiredVersion: dependencies['react-dom']
>         }
>       }
>     })
>   ],
>   build: {
>     target: 'esnext',
>     minify: false,
>     cssCodeSplit: false
>   },
> })
> ```
> 
> host app:
> 
> ```
> import { defineConfig } from 'vite'
> import react from '@vitejs/plugin-react'
> import federation from '@originjs/vite-plugin-federation'
> import {dependencies} from './package.json'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   server:{
>     host: 'local.ravenslingshot.com',
>     port: 5001,
>   },
>   preview: {
>     port: 5001
>   },
>   plugins: [
>     react(),
>     federation({
>       name: 'host-vite',
>       remotes: {
>         NavBarVite: 'http://local.ravenslingshot.com:5000/assets/remoteEntry.js'
>       },
>       shared: {
>         ...dependencies,
>         react: {
>           requiredVersion: dependencies['react']
>         },
>         "react-dom": {
>           requiredVersion: dependencies['react-dom']
>         }
>       }
>     })
>   ],
>   build: {
>     target: 'esnext',
>     minify: false,
>     cssCodeSplit: false
>   },
> })
> ```
> 
> ![image](https://user-images.githubusercontent.com/39062289/191358415-fc437a8a-642e-400a-b1d0-488f9b120455.png)

Hi!

Same error here.. can't find a fix.

**Comment by Yulingsong** [comment]
> 

me too,Did you solve the problem ？

**Comment by Yulingsong** [comment]
> > I have two react apps configured with vite and this plugin. I tried building them and served through preview, still not able to get them work together. I am not sure of what is going wrong with sharing my dependencies. I was actually sharing material-ui in the remote component (which failed), so I tried using useState but failed.
> > link to my repo https://github.com/SaiMadhav9494/vite-micro-frontend
> > remote app:
> > ```
> > import { defineConfig } from 'vite'
> > import react from '@vitejs/plugin-react'
> > import federation from '@originjs/vite-plugin-federation'
> > import {dependencies} from './package.json'
> > 
> > // https://vitejs.dev/config/
> > export default defineConfig({
> >   server:{
> >     host: 'local.ravenslingshot.com',
> >     port: 5000,
> >   },
> >   preview: {
> >     port: 5000,
> >   },
> >   plugins: [
> >     react(),
> >     federation({
> >       name: 'NavBarVite',
> >       filename: 'remoteEntry.js',
> >       exposes: {
> >         './App': './src/App.tsx'
> >       },
> >       shared: {
> >         ...dependencies,
> >         react: {
> >           requiredVersion: dependencies['react']
> >         },
> >         "react-dom": {
> >           requiredVersion: dependencies['react-dom']
> >         }
> >       }
> >     })
> >   ],
> >   build: {
> >     target: 'esnext',
> >     minify: false,
> >     cssCodeSplit: false
> >   },
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > host app:
> > ```
> > import { defineConfig } from 'vite'
> > import react from '@vitejs/plugin-react'
> > import federation from '@originjs/vite-plugin-federation'
> > import {dependencies} from './package.json'
> > 
> > // https://vitejs.dev/config/
> > export default defineConfig({
> >   server:{
> >     host: 'local.ravenslingshot.com',
> >     port: 5001,
> >   },
> >   preview: {
> >     port: 5001
> >   },
> >   plugins: [
> >     react(),
> >     federation({
> >       name: 'host-vite',
> >       remotes: {
> >         NavBarVite: 'http://local.ravenslingshot.com:5000/assets/remoteEntry.js'
> >       },
> >       shared: {
> >         ...dependencies,
> >         react: {
> >           requiredVersion: dependencies['react']
> >         },
> >         "react-dom": {
> >           requiredVersion: dependencies['react-dom']
> >         }
> >       }
> >     })
> >   ],
> >   build: {
> >     target: 'esnext',
> >     minify: false,
> >     cssCodeSplit: false
> >   },
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/39062289/191358415-fc437a8a-642e-400a-b1d0-488f9b120455.png)
> 
> Hi!
> 
> Same error here.. can't find a fix.

me too,Did you solve the problem ？

**Comment by mndbndr** [comment]
Has there been any answer to the issue of using hooks in the remote app and crashing the host app? I am unable to find a solution that works to this issue. I love Vite and want to stick with it, but I am now afraid I will have to go back to webpack to get module federation with hooks working. Thank you.

**Comment by ytftianwen** [comment]
> > > I have two react apps configured with vite and this plugin. I tried building them and served through preview, still not able to get them work together. I am not sure of what is going wrong with sharing my dependencies. I was actually sharing material-ui in the remote component (which failed), so I tried using useState but failed.
> > > link to my repo https://github.com/SaiMadhav9494/vite-micro-frontend
> > > remote app:
> > > ```
> > > import { defineConfig } from 'vite'
> > > import react from '@vitejs/plugin-react'
> > > import federation from '@originjs/vite-plugin-federation'
> > > import {dependencies} from './package.json'
> > > 
> > > // https://vitejs.dev/config/
> > > export default defineConfig({
> > >   server:{
> > >     host: 'local.ravenslingshot.com',
> > >     port: 5000,
> > >   },
> > >   preview: {
> > >     port: 5000,
> > >   },
> > >   plugins: [
> > >     react(),
> > >     federation({
> > >       name: 'NavBarVite',
> > >       filename: 'remoteEntry.js',
> > >       exposes: {
> > >         './App': './src/App.tsx'
> > >       },
> > >       shared: {
> > >         ...dependencies,
> > >         react: {
> > >           requiredVersion: dependencies['react']
> > >         },
> > >         "react-dom": {
> > >           requiredVersion: dependencies['react-dom']
> > >         }
> > >       }
> > >     })
> > >   ],
> > >   build: {
> > >     target: 'esnext',
> > >     minify: false,
> > >     cssCodeSplit: false
> > >   },
> > > })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > host app:
> > > ```
> > > import { defineConfig } from 'vite'
> > > import react from '@vitejs/plugin-react'
> > > import federation from '@originjs/vite-plugin-federation'
> > > import {dependencies} from './package.json'
> > > 
> > > // https://vitejs.dev/config/
> > > export default defineConfig({
> > >   server:{
> > >     host: 'local.ravenslingshot.com',
> > >     port: 5001,
> > >   },
> > >   preview: {
> > >     port: 5001
> > >   },
> > >   plugins: [
> > >     react(),
> > >     federation({
> > >       name: 'host-vite',
> > >       remotes: {
> > >         NavBarVite: 'http://local.ravenslingshot.com:5000/assets/remoteEntry.js'
> > >       },
> > >       shared: {
> > >         ...dependencies,
> > >         react: {
> > >           requiredVersion: dependencies['react']
> > >         },
> > >         "react-dom": {
> > >           requiredVersion: dependencies['react-dom']
> > >         }
> > >       }
> > >     })
> > >   ],
> > >   build: {
> > >     target: 'esnext',
> > >     minify: false,
> > >     cssCodeSplit: false
> > >   },
> > > })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://user-images.githubusercontent.com/39062289/191358415-fc437a8a-642e-400a-b1d0-488f9b120455.png)
> > 
> > 
> > Hi!
> > Same error here.. can't find a fix.
> 
> me too,Did you solve the problem ？

Same error here, any idea about this?

**Comment by ytftianwen** [comment]
can we reopen this issue? cause it still exist in the latest version？

**Comment by IlyaKukarkin** [comment]
This error is still happening for me on version `"1.2.0"` and it is blocking us

Managed to get Module Federation working with this package https://www.npmjs.com/package/@happening/vite-plugin-esm-federation

**Comment by norman-ags** [comment]
Is it official that this plugin doesn't support:

host - running in dev
remove - running in build

I can't make it work.

**Comment by yuvalbne** [comment]
Hi, is anybody find any solution for this issue?
![Screenshot 2023-07-16 at 18 19 36](https://github.com/originjs/vite-plugin-federation/assets/59254664/fd30dc65-c0b1-4632-b072-afe38fc90597)

**Comment by pt-hieu** [comment]
> Hi, is anybody find any solution for this issue? ![Screenshot 2023-07-16 at 18 19 36](https://user-images.githubusercontent.com/59254664/253812206-fd30dc65-c0b1-4632-b072-afe38fc90597.png)

getting the same error here, I was trying to federate module between `vite` and `webpack` but can't find a way to get `react` to work correctly

**Comment by pscl4** [comment]
![Bildschirmfoto 2023-09-15 um 13 22 49](https://github.com/originjs/vite-plugin-federation/assets/104128523/90a6a91f-8682-4026-8936-5ae7cda68696)

Hi this is still an issue. It is not working, when the react remote app is using hooks
(using build versions and _vite preview_ them host+remote)
removing the hooks, it works just fine
(using react@18.2.0 in both apps)

Host: React app - vite.config.js
`
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import federation from "@originjs/vite-plugin-federation";
import {dependencies} from './package.json'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    federation({
      name: "host-app",
      remotes: {
        remoteApp: "http://localhost:5001/assets/remoteEntry.js",
      },
      shared: {
        react: {
          requiredVersion: dependencies['react']
        },
        "react-dom": {
          requiredVersion: dependencies['react-dom']
        }
      },
    }),
  ],
  build: {
    modulePreload: false,
    target: "esnext",
    minify: false,
    cssCodeSplit: false,
  },
});
`

Remote: React app
`
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import federation from "@originjs/vite-plugin-federation";
import {dependencies} from './package.json'

export default defineConfig({
  plugins: [
    react(),
    federation({
      name: "remote_app",
      filename: "remoteEntry.js",
      exposes: {
        "./App": "./src/App.jsx",
      },
      shared: {
        react: {
          requiredVersion: dependencies['react']
        },
        "react-dom": {
          requiredVersion: dependencies['react-dom']
        }
      },
    }),
  ],
  build: {
    target: "esnext",
    modulePreload: false,
    minify: false,
    cssCodeSplit: false,
  },
});
`

**Comment by Vincent1993** [comment]
> > Hi, is anybody find any solution for this issue? ![Screenshot 2023-07-16 at 18 19 36](https://user-images.githubusercontent.com/59254664/253812206-fd30dc65-c0b1-4632-b072-afe38fc90597.png)
> 
> getting the same error here, I was trying to federate module between `vite` and `webpack` but couldn't find a way to get `react` to work correctly

i have the same problem

**Comment by stouch** [comment]
Similar problem here

```
index-dfe0d2a8.js:40 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at react_production_min.useContext (index-dfe0d2a8.js:76:6225)
```

**Comment by PhongLeeHiChat** [comment]
same problem:
```
__federation_shared_react-JNWbGlzI.js:59 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at react_production_min.useContext (__federation_shared_react-JNWbGlzI.js:59:144)
```

**Comment by stouch** [comment]
In my case it was that I imported React multiple times in my build (in my UI kit and in my project).
 So I had to fill `external` and output.globals with : 
```
  build: {
...
    rollupOptions: {
      plugins: [],
      external: ["react", "react-dom"],
      output: {
        globals: {
          react: "React",
          "react-dom": "ReactDOM",
        },
      },
    },
  },
```

**Comment by peterholcomb** [comment]
I'm also hitting this issue and I'm close to switching back to webpack to try to get it working there.  I've tried the `shared` solution as well as switching to `React.useState`, `React.useEffect`, etc... but new issues keep popping up.  

Trying the solution from @stouch didn't work for me as I get the error that `react` is a module.  @stouch if you have your full vite.config it would be great to see it to see what I'm doing wrong.  However, i would love to see a more involved example in the example apps repo that works here if possible.  Thanks for this plugin, unfortunately it doesn't seem to work for me.

**Comment by asishmindfire** [comment]
> ![image](https://private-user-images.githubusercontent.com/1982947/315262602-845adbfa-572a-4453-855d-13145a1b5d06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTIwNjEsIm5iZiI6MTcxODcxMTc2MSwicGF0aCI6Ii8xOTgyOTQ3LzMxNTI2MjYwMi04NDVhZGJmYS01NzJhLTQ0NTMtODU1ZC0xMzE0NWExYjVkMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTE1NjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzJmODg0OTAxNDgxZGYwNjY3ODliMzViNGY2ZTE0NTFmODgyOWFhM2Y2ZGJlY2UyNzI5OWRlNzk3N2RkOTUyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ArpFjtPYPLt6DDCc-Yw_T1we_Kx3I-WGg8FhntQM4UU)
> 
> Same error....
> 
> host - build preview remote - build preview
> 
> remote using https://lexical.dev/, if not using this lib, no issues.

Any solutions ???

**Comment by DileepSreepathi** [comment]
I am using the example for two react apps , but on host getting the issue , it is unable to load the module from remote app .
please provide the fix on this . 
<img width="836" alt="image" src="https://github.com/user-attachments/assets/e458ff89-e927-46a7-a812-23893fb77084">
