### ISSUE TITLE
Invalid VNode type: Symbol() error

### ISSUE THREAD

**Issue by halkhalil** [originjs/vite-plugin-federation#178]
```
<template> 
<div>
    **whats is this**
    <h1>Hello from exposed This is the HelloWorld vue from remote</h1> 
</div>
</template>
```
remote component from a host app some elements "whats is this" text is missing and the following error is on console
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid VNode type: Symbol() (symbol) 

![image](https://user-images.githubusercontent.com/10109322/165747383-1bb1cc0e-599b-4da0-85af-91e812f45957.png)

but if the remote is run independently txt "what's is this" is properly rendered n no errors

![image](https://user-images.githubusercontent.com/10109322/165747281-25024bf3-79a2-48f0-871e-c6fdf371d570.png)

**Comment by ruleeeer** [comment]
Can you provide a repository for replication? I can't be sure what the problem is based on the error message alone

**Comment by halkhalil** [comment]
hi
I am using [https://github.com/ybom77/demo-vite.git](url)
and i notice that vite versions  "2.7.2" to "vite": "2.8.6"  works without errors

![image](https://user-images.githubusercontent.com/10109322/166088947-6473a538-ef72-4459-bd60-4fcdf4f0c48d.png)
but "vite": "2.9.0", and above fails
![image](https://user-images.githubusercontent.com/10109322/166089096-916a71ed-2fb3-44ea-b298-9d4b9b21a533.png)
```
  "dependencies": {
    "primevue": "3.10.0",
    "vue": "3.2.33"
  },
  "devDependencies": {
    "@babel/types": "^7.17.10",
    "@originjs/vite-plugin-federation": "1.1.5",
    "@vitejs/plugin-vue": "2.3.1",
    "typescript": "^4.4.4",
    "unplugin-vue-components": "^0.17.11",
    "vite": "2.9.6",
    "vue-tsc": "0.34.11"
  }
```

**Comment by ruleeeer** [comment]
Let me see what vite has updated

**Comment by ruleeeer** [comment]
@halkhalil Hi
I checked the recent vite update and found a little something [relevant this](https://github.com/vitejs/vite/pull/6534/files#diff-4a49b457ff0fce41061261711fc1d5e95385af670880cebae5fca2d4807103f0)
can be added as shown in that document
``` js
import { splitVendorChunkPlugin } from 'vite'
module.exports = defineConfig({
  plugins: [splitVendorChunkPlugin()]
})
```
Go to the config file and the project will works.

**Comment by ruleeeer** [comment]
I will change the plugin to fit `vite v2.9.0` and above, thank you for your issue
