### ISSUE TITLE
Whether communication with webPack built projects is supported

### ISSUE THREAD

**Issue by huntJs** [originjs/vite-plugin-federation#180]
### Additional context

for example  project A was build using vite(MF), and project B was build using webpack5(MF), so my question is whether the project A  can be used as host or remote ,thanks~

**Comment by ruleeeer** [comment]
vite as remote or host side is allowed, here are some examples to show the mixed use with webpack module federation(please focus on the folder project name with webpack)
https://github.com/originjs/vite-plugin-federation/tree/main/packages/examples 
but I just tried a few simple examples, do not know if it is feasible in complex scenarios, if there are problems welcome to use the issue report

**Comment by anhnt2310** [comment]
@ruleeeer What about host (webpack) - remote (vite) ? I couldn't find any example for that.

**Comment by flyfishzy** [comment]
Yes, but we have only implemented webpack configured as esm format, other formats may not be supported.

**Comment by flyfishzy** [comment]
Hi @huntJs , webpack have been supported and compatible with the `esm` `systemjs` `var` format.
