### ISSUE TITLE
Source maps generation

### ISSUE THREAD

**Issue by matrunchyk** [originjs/vite-plugin-federation#181]
Hello and thank you for your amazing work!

When building an app with the plugin enabled, it throws at me a lot of warning like so:

> Sourcemap is likely to be incorrect: a plugin (originjs:federation) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

Is it possible to get rid of this issue?

### Versions

- originjs: 1.1.5
- node: v16+

**Comment by ruleeeer** [comment]
Hi , @matrunchyk 
This may be an issue for improvement, as the plugin modifies the generated source code during compilation, but I didn't handle the sourceMap additionally, and turning off sourceMap generation suppresses the warning

**Comment by ruleeeer** [comment]
I will try to fix the problem by generating a sourceMap while modifying
