### ISSUE TITLE
Plugin configuration not working

### ISSUE THREAD

**Issue by Tordek** [originjs/vite-plugin-federation#192]
### Versions

- originjs: latest

### Reproduction

Make a fresh install of vite+react+ts, and install this script with the configuration in the README

### What is Expected?

It should work.

### What is actually happening?

localhost:3000/remoteEntry.js returns 404. No compilation errors are displayed.

**Comment by ruleeeer** [comment]
Hi , Different component tools may result in different paths, in general the access path for vite may be `localhost:3000/assets/remoteEntry.js`, but this is not absolute as some people will change the output directory causing the access path to change

**Comment by Tordek** [comment]
Given a configuration like the one in the readme, where should the file be expected? It should be documented.

The `remotes` configuration also seems to do nothing; using `const foo = () => import('foo/Button')` results in a compilation error and no attempt is done to load the remote in the browser. The documentation example for `import` should match the configuration above (and the two configuration examples should match each other).

**Comment by Tordek** [comment]
https://github.com/Tordek/vite-repro

**Comment by Tordek** [comment]
I have tried the examples in this repo with no results.

Running `rollup-host` results in the page attempting to load `/dist/index.js` and failing with a 404. Runnint `rollup-remote` and attempting to open `localhost:5001/remoteEntry.js` as indicated in `rollup-host`'s `remote` returns a 404.

Please include `package-lock.json` or `yarn.lock` files with your examples.

**Comment by Tordek** [comment]
After wasting more time, the issue is that this plugin cannot be used in development mode; only when `vite build` is executed is the file created.
