### ISSUE TITLE
ContentHash for exposed Components

### ISSUE THREAD

**Issue by MarkusJLechner** [originjs/vite-plugin-federation#197]
### Is your feature request related to a problem? Please describe.

Every File is generated without a content hash. Proper browser cache is not possible, only no-cache allows components to update.
**remoteEntry.js** should use no-cache anyway, as it is the entry point for the mapped components.

### Describe the solution you'd like

When generating `__federation_expose_` it could be possible to read the files, content hash them and append the hash to the name.
This works easily on **expose**. **css** imports also need an hash, this is done with the `assetFileNames` option and `[hash]` 
 string like `${chunkInfo.name}_[hash].css`

Maybe something like this in **utils**:
https://github.com/originjs/vite-plugin-federation/blob/ced3dd9980f24d0b019cf7929e2c56f702489589/packages/lib/src/utils/index.ts#L56-L70
replace with
```js
export function parseExposeOptions(
  options: VitePluginFederationOptions
): (string | ConfigTypeSet)[] {
  return parseOptions(
    options.exposes,
    (item) => {
      return {
        import: item,
        name: undefined,
        contentHash: createContentHash(item) // this is added
      }
    },
    (item) => ({
      import: Array.isArray(item.import) ? item.import : [item.import],
      name: item.name || undefined,
      contentHash: createContentHash(item.import) // this is added. Array.isArray(item.import) is making some problems, see #196
    })
  )
}

// Creates a content hash of the given file
export function createContentHash(path: string): string {
  const content = fs.readFileSync(path, { encoding: 'utf-8' })
  return Crypto.createHash('md5')
    .update(content)
    .digest('hex')
    .toString()
    .slice(0, 6)
}

// This will sanitize names and add a content hash on the end
const nameCharReg = new RegExp('[0-9a-zA-Z@_-]+')
export function getExposeImportName(item: string | ConfigTypeSet): string {
  if (typeof item === 'string') {
    return item
  }

  return `${removeNonRegLetter(item[0], nameCharReg)}_${item[1].contentHash}`
}
```

Change in
https://github.com/originjs/vite-plugin-federation/blob/ced3dd9980f24d0b019cf7929e2c56f702489589/packages/lib/src/prod/expose-production.ts#L32
and
https://github.com/originjs/vite-plugin-federation/blob/ced3dd9980f24d0b019cf7929e2c56f702489589/packages/lib/src/prod/remote-production.ts#L193-L197
```diff
---moduleMap += `\n"${item[0]}":()=>{
---      ${DYNAMIC_LOADING_CSS}('${DYNAMIC_LOADING_CSS_PREFIX}${exposeFilepath}')
---      return __federation_import('\${__federation_expose_${item[0]}}').then(module =>Object.keys(module).every(item => exportSet.has(item)) ? () => module.default : () => module)
---    },`
+++moduleMap += `\n"${item[0]}":()=>{
+++      ${DYNAMIC_LOADING_CSS}('${DYNAMIC_LOADING_CSS_PREFIX}${exposeFilepath}')
+++      return __federation_import('\${__federation_expose_${getExposeImportName(
+++        item
+++      )}}').then(module =>Object.keys(module).every(item => exportSet.has(item)) ? () => module.default : () => module)
+++    },`
```

Now the file and mapping is generated like `__federation_expose_V1BaseHeaderLine_46c3cd.js`

Tell me what you think

### Describe alternatives you've considered

I can't think of an alternative. The browser cache works with filenames. If they don't change, a old version is delivered or always fetched, which increases page load time.

### Additional context

![image](https://user-images.githubusercontent.com/48199873/174486665-f227d868-d193-471b-8242-9f555886b4f0.png)

Seen on this picture how it looks.
CSS hash is not present on this screenshot, archived with `[hash]`

**Comment by ruleeeer** [comment]
Already released 1.1.7

**Comment by zwStar** [comment]
@MarkusJLechner @ruleeeer Disturb both of you,  now i update this feature version, but i find a problem is that you calc the content hash is according to source content, when it dependence change, it will calc the same hash, so it is need to calc the hash after be transform?

**Comment by ruleeeer** [comment]
@zwStar I understand the problem you are talking about, but in general the source code is consistent, then the code generated by the plug-in should also be consistent (unless the plug-in has undergone a major upgrade change), another situation is that if someone writes a plug-in to change the code generated by federation, it may also cause problems

**Comment by ruleeeer** [comment]
@zwStar This is a problem, it just seems to me that he is not so easy to trigger and form the impact, after I have time to try to fix it

**Comment by zwStar** [comment]
> @zwStar This is a problem, it just seems to me that he is not so easy to trigger and form the impact, after I have time to try to fix it

As i know, rollup calc hash is according to bundle content, but the plugin in the transform hooks use this emitFile cannot get this bundle code to calc, so i has a ideal is not use this.emitFile but using input(add those export module to rollup input), which can use rollupOptions.chunkFileNames to auto calc the hash, have you had this ideal and there any problem with this design?

**Comment by ruleeeer** [comment]
@zwStar Probably the idea is similar, either explore changing the name of the file after the eximFile (e.g. during the chunk generation phase) or rely on rollup to generate it directly and automatically
