### ISSUE TITLE
SyntaxError in Safari 13.1.3

### ISSUE THREAD

**Issue by apankun** [originjs/vite-plugin-federation#203]
### Versions

- originjs:  1.1.6
- node: 16.14.2

### Reproduction
   federation({
      name: "app", 
      // filename: "remoteEntry.js", 
     remotes: {
        "xx-components": "/xx-components/assets/remoteEntry.js", 
      },
            shared: ['vue', 'tdesign-vue-next'],
    })],

### Steps to reproduce

it doesn't work in Safari 13.1.3 
SyntaxErrror would be found in console like 

/** SyntaxError: Unexpected identifier '__federation_method_getRemote'. Expected ';' after variable declaration. **/

**Comment by flyfishzy** [comment]
Maybe duplicate of  https://github.com/originjs/vite-plugin-federation/issues/205
