### ISSUE TITLE
Preload helper is loading the resources from wrong urls

### ISSUE THREAD

**Issue by anhnt2310** [originjs/vite-plugin-federation#210]
### Versions

- originjs: ^1.1.6
- node: v16.15

### Reproduction

I see the file `preload-helper.js` that is bundled could be wrong

![image](https://user-images.githubusercontent.com/80698274/177468593-d8488709-7aa0-40e8-9fd1-f91ee9a42480.png)

You can see in the above image, code will automatically set the URL with the base URL `/`, after that, It will be appended to `<header>` of the web.

![image](https://user-images.githubusercontent.com/80698274/177468871-d83896a9-35f8-4014-8e89-6f5f97cd26ac.png)

But the host-app fetches `preload-helper.js` from remote-app and run on host-app. Actually, the host-app doesn't have those.
So we will get some errors like this

![image](https://user-images.githubusercontent.com/80698274/177469169-c9d797cc-71cf-49b5-a65f-394262409cf6.png)

Did I get this problem right?

My `vite.config.ts`

```javascript
export default defineConfig(({ command, mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const antdLessConfig = createAntdLessConfig(env);

  return {
    plugins: [
      react(),
      eslint({
        cache: mode === 'production',
        emitError: true,
        emitWarning: mode === 'development',
      }),
      relay,
      dynamicImport(),
      federation({
        name: 'remoteULK',
        filename: 'remoteEntry.js',
        exposes: {
          './ULKApp': './src/bootstrap',
        },
        shared: {
          react: { requiredVersion: deps.react },
          'react-dom': { requiredVersion: deps['react-dom'] },
        },
      }),
      vitePluginImp({
        optimize: true,
        libList: [
          {
            libName: 'antd',
            libDirectory: 'es',
            style: (name) => `antd/es/${name}/style`,
          },
        ],
      }),
    ],
    resolve: {
      alias: [
        {
          find: '@',
          replacement: path.resolve(__dirname, 'src'),
        },
        {
          find: '~',
          replacement: path.resolve(__dirname),
        },
      ],
    },
    server: {
      open: true,
      port: +env.DEV_PORT,
      // https: 'http',
    },
    preview: {
      port: +env.DEV_PORT,
    },
    build: {
      target: 'esnext',
      minify: false,
      cssCodeSplit: false,
    },
    css: {
      preprocessorOptions: {
        ...antdLessConfig,
      },
    },
  };
});

```

### What is Expected?

Loading resources properly

**Comment by AndreiSoroka** [comment]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/6079139/182252284-ad06269d-7d16-49eb-bbe0-87d82c59b647.png">
Same problem, each component get wrong url from `preload-helper.js`

but after that I can get component with right url from chunk
<img width="312" alt="image" src="https://user-images.githubusercontent.com/6079139/182252860-4298ce28-e425-46f9-b9fd-77c31ae80b01.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/6079139/182252901-7fac615e-c686-42b8-8df5-8f4e05474eca.png">


I found temporary solution:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/6079139/182253026-fa725c1e-c150-4ab5-b979-0aae06c939b4.png">
need to add strict `base` option. But it is wrong way and hard to support if your application work in 2 envs

**Comment by AndreiSoroka** [comment]
@ruleeeer Sorry for ping, but maybe do you have any idea?

**Comment by ruleeeer** [comment]
@AndreiSoroka How can I reproduce the problem？

**Comment by AndreiSoroka** [comment]
> @AndreiSoroka How can I reproduce the problem

I'll create reproduce repo this week

**Comment by AndreiSoroka** [comment]
@ruleeeer https://github.com/AndreiSoroka/mf-reproduce-vite-preload

strange, but last time there were no problems with styles 😄 

![ezgif-2-1c7dd1f3cc](https://user-images.githubusercontent.com/6079139/185708656-131873bd-a007-4912-95c6-398a04fdc4c7.gif)

**Comment by ruleeeer** [comment]
@AndreiSoroka 
HI , thx for your  reproduce repo
I changed the configuration and I see it locally like this and it seems to work

![image](https://user-images.githubusercontent.com/70385062/186870230-5f14ca3c-c024-4a30-abfd-753a9ef19b0e.png)
![image](https://user-images.githubusercontent.com/70385062/186870277-a2d973f1-9971-495f-b933-adb6bf3440e4.png)

you only need to add `cssCodeSplit:false` into `build:{...}` in `remote-app/vite.config.js`
![image](https://user-images.githubusercontent.com/70385062/186870931-d3874be1-998e-4257-8316-3f2146d0d10e.png)
