### ISSUE TITLE
Add webpack host and vite/rollup remote example

### ISSUE THREAD

**Issue by Yitzhakpro** [originjs/vite-plugin-federation#223]
### Is your feature request related to a problem? Please describe.
I have tried to make a basic demo of webpack host that uses vite remote component, but I failed to do that.

### Describe the solution you'd like
maybe you can add a basic example that instead of all vite/rollup host, include a webpack host example

**Comment by hmellahi** [comment]
@flyfishzy did you manage to fix the issue?

**Comment by ruleeeer** [comment]
The webpack-related examples are already available here https://github.com/originjs/vite-plugin-federation/tree/main/packages/examples
![图片](https://user-images.githubusercontent.com/70385062/182323048-95d325b4-96d7-4e13-bad7-ea6d20bf01d3.png)

**Comment by ruleeeer** [comment]
But it looks like the EXAMPLE in the README is not updated, I will update this part later

**Comment by hmellahi** [comment]
@ruleeeer Thank you

**Comment by flieks** [comment]
Thanks 
and what about an example in a cunsumer/host that doesn't use webpack (example blazor or plain JS) ?

**Comment by flyfishzy** [comment]
EXAMPLE & README have been updated.
