### ISSUE TITLE
Avoid CORS when requesting remotes modules from host

### ISSUE THREAD

**Issue by robertovg** [originjs/vite-plugin-federation#249]
### Is your feature request related to a problem? Please describe.

We are migrating a React MFEs project from Webpack to Vite and when pulling remotes components like described in the documentation:

We expose the host and remotes in different subdomains.

https://dtca-backoffice.evqtnet.test:8000/ (host)
https://dtca-ledger.evqtnet.test:8000/remoteEntry.js (remote)

```js
const myButton = React.lazy(() => import('remote/myButton'))
```

The request contains the following header:

```
Sec-Fetch-Mode: cors
```

And because of that, we get a CORS error when loading them.

![Screen Shot 2022-09-30 at 11 42 03 AM](https://user-images.githubusercontent.com/570679/193242726-92dba54c-5843-4f8e-b65e-dbec0db8b983.png)

Using Webpack with [module-federation](https://webpack.js.org/concepts/module-federation/) same request (in a different environment), same contains the opposite header.

```
sec-fetch-mode: no-cors
```

### Describe the solution you'd like

We would like to be able to define custom headers for module requests so we can specify `no-cors` option to avoid this problem.

**Comment by flyfishzy** [comment]
Vite-plugin-federation uses ES Modules `import` to load remote js modules, which automatically adds the CORS headers.In other words, if a module script is fetched from another origin, the remote server must supply a header Access-Control-Allow-Origin allowing the fetch.

**Comment by ruleeeer** [comment]
I think cors should be set up on the server rather than the front end, as in the example project (of course, in general production environments are more likely to use nginx)
``` js
devServer: {
    static: {
      directory: path.join(__dirname),
    },
    compress: true,
    port: 5001,
    hot: true,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
      "Access-Control-Allow-Headers":
        "X-Requested-With, content-type, Authorization",
    },
  },
```

**Comment by vivipure** [comment]
I wrote an adaptation plugin that takes advantage of Vite's proxy capabilities.
```ts
function adaptiveModuleFederationPlugin(federationConfig) {
  const adpativePlugin = () => ({
    name: "adaptiveModuleFederation",
    config(config, { command }) {
      if (command === "serve") {
        if (!config.server.proxy) {
          config.server.proxy = {};
        }

        const remotes = federationConfig.remotes;
        const remoteKeys = Object.keys(remotes);

        remoteKeys.forEach((key) => {
          const urlConfig = remotes[key];
          let url = "";
          if (typeof urlConfig === "string") {
            url = urlConfig;
          } else if (typeof urlConfig === "object") {
            url = urlConfig.external;
          }
          const preffixUrl = url.substring(0, url.lastIndexOf("/"));
          const endUrl = url.substring(url.lastIndexOf("/"));
          const proxyPath = "/proxy" + key;
          const reg = new RegExp(`^${proxyPath}`);

          config.server.proxy[proxyPath] = {
            target: preffixUrl,
            changeOrigin: true,
            rewrite: (path) => path.replace(reg, ""),
          };

          const updateUrl = proxyPath + endUrl;

          if (typeof urlConfig === "string") {
            federationConfig.remotes[key] = updateUrl;
          } else if (typeof urlConfig === "object") {
            federationConfig.remotes[key].external = updateUrl;
          }
        });
      }
    },
  });

  return [adpativePlugin(), federation(federationConfig)];
};
```
Use in Vite
```
plugins: [
      adaptiveModuleFederationPlugin({
        // ... your ferderation config
      })
]
```

**Comment by mostafa-raafat** [comment]
@robertovg did you able to solve this issue I have the same problem and not able to fix it 
could you share your `vite.config` Thank you.

**Comment by robertovg** [comment]
Here you have a working example: https://github.com/originjs/vite-plugin-federation/issues/242#issuecomment-1283841548

**Comment by robertovg** [comment]
Thought the CORs problem is something to be fixed in the infra.

**Comment by mostafa-raafat** [comment]
@robertovg I already try it and it's not working https://stackblitz.com/edit/vite-plugin-federation-shared-libs-problems-hierarchy

**Comment by robertovg** [comment]
I just tried, and it is, actually, it build both (host and MFE) and exposes them correctly, you might need to click on the reload button to consume the project after the build has finished :)
<img width="2672" alt="Screenshot 2023-03-01 at 12 09 59 PM" src="https://user-images.githubusercontent.com/570679/222123282-c9e70258-ac85-4bf9-ab41-2f87785f547b.png">

**Comment by mostafa-raafat** [comment]
@robertovg the app work until i replace localhost with remote url then it crush and with `CORS` issue
<img width="1364" alt="Screenshot 2023-03-01 at 12 20 50" src="https://user-images.githubusercontent.com/43439787/222125268-41419a59-aeea-404c-b327-faa3aae2f619.png">
<img width="1176" alt="Screenshot 2023-03-01 at 12 21 02" src="https://user-images.githubusercontent.com/43439787/222125313-0e6d6792-78f2-40cd-832d-b88321b0c2bf.png">

**Comment by robertovg** [comment]
Have you tried to modify the Vite dev server as you can see [up here](https://github.com/originjs/vite-plugin-federation/issues/249#issuecomment-1276053091)

**Comment by fukai007** [comment]
remote 的服务器 设置跨域即可， nginx 配置如下 

    location /baseframe {
        alias   /vue/;
        #允许跨域请求的域，* 代表所有
        add_header 'Access-Control-Allow-Origin' *;
        #允许请求的header
        add_header 'Access-Control-Allow-Headers' *;
        #允许带上cookie请求
        add_header 'Access-Control-Allow-Credentials' 'true';
        #允许请求的方法，比如 GET,POST,PUT,DELETE
        add_header 'Access-Control-Allow-Methods' *;
        try_files $uri $uri/ /index.html =404;
    }
