### ISSUE TITLE
Invalid remoteEntry.js created when building in watch mode

### ISSUE THREAD

**Issue by robinbullock** [originjs/vite-plugin-federation#253]
### Versions

- vite-plugin-federation: v1.1.9
- vite: v3.1.8

### Reproduction

[Reproduction](https://github.com/robinbullock/vite-federation-watch-bug). Instructions in README.md for that repo, and below.

#### In `/host`

- `npm install`
- `npx vite start`

#### In `/remote`

- `npm install`
- `npx vite build --watch`
- In a separate terminal, run `vite serve`

#### Reproduction

- Open http://localhost:5173 and you'll see "Remote app (1)", indicating that module federation works correctly
- Make a change to `remote/src/App.tsx` (e.g. change the 1 to 2) and wait for the browser to reload
- You'll see the following error trace in the Chrome console:

  ```
  Uncaught TypeError: cssFilePaths.forEach is not a function
      at dynamicLoadingCss (remoteEntry.js:54:20)
      at ./App (remoteEntry.js:43:7)
      at Module.get (remoteEntry.js:66:33)
      at __x00__virtual:__federation__:83:73
      at async App.tsx:8:36
  dynamicLoadingCss @ remoteEntry.js:54
  ./App @ remoteEntry.js:43
  get @ remoteEntry.js:66
  (anonymous) @ __x00__virtual:__federation__:83
  ```
  
- Stop the `vite build` process and restart it
- Wait for the browser to reload
- Note that the change has now taken effect

### What is Expected?
- `dynamicLoadingCss` is called with a valid argument
- The file name for the exposed module is correctly replaced inside the module map

### What is actually happening?
Here is a snippet of the `remoteEntry.js` from the first build, re-formatted for readabililty.

```javascript
let moduleMap = {
  "./App": () => {
      dynamicLoadingCss([]);
      return __federation_import('./__federation_expose_App.18b8f0a3.js')
        .then(module => Object.keys(module)
        .every(item => exportSet.has(item)) ? () => module.default : () => module)
  }
};
```

Now here's the same snippet but from the second build (in watch mode).

```javascript
let moduleMap = {
  "./App": () => {
      dynamicLoadingCss('__v__css__/Users/robin/d/vite-federation-watch-bug/remote/src/App.tsx');
      return __federation_import('${__federation_expose_./App}')
        .then(module => Object.keys(module)
        .every(item => exportSet.has(item)) ? () => module.default : () => module)
    }
};
```

There are two problems here that I can see.

1. `dynamicLoadingCss` is called with a string when it expects an array
2. The variable for the exposed module inside the module map fails to get replaced

**Comment by robinbullock** [comment]
I'm happy to attempt to fix this issue but I could do with some help getting started. I can see that the snippet I've pasted above is from generated code, but I only see this code generation happening once, inside [`prodExposePlugin`](https://github.com/originjs/vite-plugin-federation/blob/main/packages/lib/src/prod/expose-production.ts#L26), but I don't see it being called for subsequent builds.

**Comment by rubixibuc** [comment]
I'm having this same issue

**Comment by flyfishzy** [comment]
Ah, the `vite build --watch` mode might have different callback events, and this scenario we missed. Thank you for the detailed issue analysis, the problem should be in the prodExposePlugin.

**Comment by Itarn** [comment]
There is an another question. In `dynamicLoadingCss([]);` cssFiles is missing.

### Version
the same versions with robinbullock's demo

vite-plugin-federation: v1.1.9
vite: v3.1.8

### Reproduction
[Reproduction](https://stackblitz.com/edit/vitejs-vite-bpv9nf)

### Solution(Maybe be wrong)
[codeLine](https://github.com/originjs/vite-plugin-federation/blob/main/packages/lib/src/prod/expose-production.ts#L182)

```
 .......
  ;[fileBundle.fileName, ...fileBundle.imports].forEach(addDepCss)

  // viteMetadata importedCss
  if (
    fileBundle.viteMetadata &&
    fileBundle.viteMetadata.importedCss
  ) {
    fileBundle.viteMetadata.importedCss.forEach((v) => {
      depCssFiles.add(v)
    })
  }

return `[${[...depCssFiles]
        .map((d) => JSON.stringify(basename(d)))
        .join(',')}]`
......
```

Apologies for I don't make a pr.I think the solution maybe incomplete. But in my local env it's works.

Thx very much.

**Comment by wkei** [comment]
Yes, I met the same issue. I can only preview the latest federation outcome with rerunning build command manually.
