### ISSUE TITLE
导入Vue 文件,样式不生效

### ISSUE THREAD

**Issue by chinaSoftMobile** [originjs/vite-plugin-federation#277]
### Versions

- vite-plugin-federation: 1.1.11
- vite: 2.9.15 

### Reproduction

导入 vue 文件 由于 data-v-XXX 生成的指令标识,导致样式不生效

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by flyfishzy** [comment]
Try the cssInjectedByJsPlugin? Here is an example https://github.com/originjs/vite-plugin-federation/blob/main/packages/examples/vue3-advanced-demo/team-green/vite.config.ts

**Comment by chinaSoftMobile** [comment]
This problem has been solved,thanks。 export need 
` federation({
                name: 'spms-cloud-customer-app', 
                remotes: {
            
                },
                exposes: {
                },
                shared: ['vue']
            })`
