### ISSUE TITLE
the last version of vite-plugin-federation not have dist/*

### ISSUE THREAD

**Issue by pingzidong** [originjs/vite-plugin-federation#290]
### Versions

- vite-plugin-federation: 
- vite: 

### Reproduction

<details open>
<summary>the last version of vite-plugin-federation cannot have dist/*</summary>
<br>

</details>

### Steps to reproduce
install the lastest version of vite-plugin-federation
### What is Expected?
can use 
### What is actually happening?
can not use

**Comment by flyfishzy** [comment]
Thx! We have released a new version.

**Comment by pingzidong** [comment]
您的邮件已收到，我会定时查收。祝您身体健康，工作顺利！
