### ISSUE TITLE
prevent shared dependencies from generating

### ISSUE THREAD

**Issue by tky753** [originjs/vite-plugin-federation#293]
### Is your feature request related to a problem? Please describe.

I found that after the remote side built, I deleted `__federation_shared_xxx` shared dependencies, my host still works.
So will there be an option to prevent the shared dependencies from generating?

**Comment by zgid123** [comment]
@tky753 I think you should remove `shared` option to archive your goal

**Comment by tky753** [comment]
> I think you should remove `shared` option to archive your goal
If I remove `shared` option, the shared dependencies will be weaved into chunk-xxxx.js,
that's not what I expected.

**Comment by zgid123** [comment]
hmm. I don't get your idea. Lemme check my side project's build folder and try

**Comment by tky753** [comment]
> hmm. I don't get your idea. Lemme check my side project's build folder and try

I have two projects: a host and a remote. They both reference Vue package. 
For saving space and preventing duplicate imports, I want the `__federation_shared_vue.js` only generated on the host side.
Is it possible?

**Comment by Kgnx7** [comment]
> > hmm. I don't get your idea. Lemme check my side project's build folder and try
> 
> I have two projects: a host and a remote. They both reference Vue package. For saving space and preventing duplicate imports, I want the `__federation_shared_vue.js` only generated on the host side. Is it possible?

I have a similar problem. If on remote side vite config `base` property is specified all remote shared deps does not shared with host (

**Comment by zgid123** [comment]
I see. I will have a look later. I am busy with my deadline recently. What do you think about this @ruleeeer?

**Comment by ruleeeer** [comment]
I think I understand what you are saying, you want to delete the shared file generated on the remote side, because if the host side provides a proper shared file, the shared on the remote side will be of no use except to increase the package size

**Comment by ruleeeer** [comment]
Consider adding a configuration to remove the generation of unnecessary shared

**Comment by ruleeeer** [comment]
I have added a configuration. This will cause the remote side to not generate a `shared` chunk for `vue`
``` js
shared: {
  vue: {
    generate: false
  }
}
```

**Comment by linux-nerd** [comment]
What will happen if the host is also a remote to some other host?

**Comment by front-refined** [comment]
> 如果该主机对于其他主机来说也是远程主机，会发生什么情况？

我尝试过，一切良好，但是会生成奇怪的文件，
<img width="868" alt="image" src="https://github.com/user-attachments/assets/3c50a06b-dfe9-4feb-bb50-5afd40972945">
不过我调试了代码，并不会运行这段代码，所以就不再去深入研究了。
