### ISSUE TITLE
builde miss css chunk

### ISSUE THREAD

**Issue by AboyL** [originjs/vite-plugin-federation#303]
### Versions
- vite-plugin-federation: 1.1.12
- vite: 3.2.5

### Reproduction

the vite.config.ts is
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import federation from "@originjs/vite-plugin-federation";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    federation({
      name: "remote_app",
      filename: "remoteEntry.js",
      // 导出模块声明
      exposes: {
        "./Button": "./src/components/Button.vue",
      },
      // 共享依赖声明
      shared: ["vue"],
    }),
  ],
  build: {
    target: 'esnext',
    minify: false,
  },
})

```

Run the vite build command and view it as the generated dist folder。The contents of the dynamicLoadingCss array in the remoteEntry file are empty。If the component is introduced remotely on another page, the styling will be dropped。

like the issue https://github.com/originjs/vite-plugin-federation/issues/45

### Steps to reproduce

1. new a vite project and add vite-plugin-federation
2. copy the config and new a component called Button.vue in src/components
3. run vite build and see the remoteEntry.js
4. the dynamicLoadingCss array is empty

### What is Expected?
The css can be loaded correctly

### What is actually happening?
the dynamicLoadingCss array is empty

and i have submitted a fix for this bug。
https://github.com/originjs/vite-plugin-federation/pull/302

**Comment by flyfishzy** [comment]
Thanks for your contribution! It looks great!
