### ISSUE TITLE
There's an example with shared stores?

### ISSUE THREAD

**Issue by oceangravity** [originjs/vite-plugin-federation#314]
### Is your feature request related to a problem? Please describe.

I'm wondering if a Pinia store can be shared through several modules, in example:

![Dibujo sin título](https://user-images.githubusercontent.com/5217583/211667121-ce534c37-691f-4185-94e7-90ea274a9e48.png)
Is this possible? Thanks!

**Comment by flyfishzy** [comment]
Please see our examples, eg. [vue3-demo-webpack-esm-esm](https://github.com/originjs/vite-plugin-federation/tree/main/packages/examples/vue3-demo-webpack-esm-esm)

**Comment by oceangravity** [comment]
Thank you very much, I saw those examples, but there seems to be no Pinia store shared between modules as an attempt to achieve 😥

**Comment by ruleeeer** [comment]
https://github.com/originjs/vite-plugin-federation/pull/317

> Thank you very much, I saw those examples, but there seems to be no Pinia store shared between modules as an attempt to achieve disappointed_relieved

**Comment by oceangravity** [comment]
Oh great, thank you so much! @ruleeeer !!!
