### ISSUE TITLE
Incorrect error handling when loading module

### ISSUE THREAD

**Issue by Somft** [originjs/vite-plugin-federation#316]
When federated module fails to load, promise returned from import(...) is never rejected.

In code responsible for loading module(`packages/lib/src/prod/remote-production.ts` and `packages/lib/src/dev/remote-development.ts `) new Promise is created, but it is not using 'reject'.

https://github.com/originjs/vite-plugin-federation/blob/9c1ac700f32bd263678cc4f9ab07334e49b3aa90/packages/lib/src/prod/remote-production.ts#L90-L100

https://github.com/originjs/vite-plugin-federation/blob/9c1ac700f32bd263678cc4f9ab07334e49b3aa90/packages/lib/src/prod/remote-production.ts#L103-L117

**Comment by flyfishzy** [comment]
Thank you very much for your reminder. This does seem to be a problem.

**Comment by flyfishzy** [comment]
In this scenario we are only interested in successful outcomes. Error cases will implicitly throw exceptions, there is no need to add `reject`. For example, if the remote sever goes down, we will get an `uncaught in promise error`.
