### ISSUE TITLE
Broken sourcemaps when used with Rollup 

### ISSUE THREAD

**Issue by bardisg** [originjs/vite-plugin-federation#336]
When used with rollup the generated sourcemaps do not have mappings.

### Versions

- vite-plugin-federation: 1.1.14
- rollup: 3.9.1 - 3.10.0

### Reproduction

Just set sourcemap: true for the output of the packages/examples/basic-host-remote/rollup-host.
Generated source map in dist folder has empty mappings.

<details open>
<summary>Rollup config with sourcemap</summary>
<br>

```
import federation from "@originjs/vite-plugin-federation";

import pkg from "./package.json" assert { type: "json" };

export default {
  input: "src/index.js",
  preserveEntrySignatures: false,
  plugins: [
    federation({
      remotes: {
        remote_app: "http://localhost:5001/remoteEntry.js",
      }
    })
  ],
  output: [{ format: "esm", dir: pkg.main, sourcemap: true }],
};
```
</details>

### Steps to reproduce
- add sourcemap true in rollup config of the remote-host package
- pnpm build (in the remote-host package folder)

### What is Expected?
Expected to have generated sourcemap file with mappings

### What is actually happening?
Generated sourcemap file has empty mappings
```
{"version":3,"file":"index.js","sources":[],"sourcesContent":[],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"}
```

**Comment by bardisg** [comment]
I believe, if my understanding is correct, that based on rollup documentation for example transformer at https://rollupjs.org/plugin-development/#example-transformer the transform method at https://github.com/originjs/vite-plugin-federation/blob/main/packages/lib/src/index.ts#L150 should return an object or type { code: result, map: Sourcemap | null } instead of just the result code

**Comment by bardisg** [comment]
Seems my issue is resolved by this diff in file https://github.com/originjs/vite-plugin-federation/blob/main/packages/lib/src/prod/remote-production.ts#L387:

-                return magicString.toString();
+                return {
+									code: magicString.toString(),
+									map: magicString.generateMap({
+										hires: false,
+										file: id,
+										includeContent: false,
+										source: undefined
+									})
+								};

**Comment by flyfishzy** [comment]
Duplicate with #355

**Comment by ruleeeer** [comment]
Follow #355 to close it together. If there is a problem, you can reopen it.
