### ISSUE TITLE
vue3-advanced-demo工程交互问题以及element-plus组件展示不出来

### ISSUE THREAD

**Issue by Yulingsong** [originjs/vite-plugin-federation#340]
### Versions

- vite-plugin-federation: 1.1.14
- vite: 4.0.3

使用的是官方代码中vue3-advanced-demo工程

出现的现象：
## 第一个问题
未进行任何代码修改，安装依赖之后
本地工程启动之后
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/13497831/216210080-73e763cd-8193-4294-8e90-36368d99845d.png">

点击按钮之后上方未变色；

## 第二个问题：就是在子工程team-blue中远程组件中添加element-plus组件

随便在buy中添加button组件
```
<template>
    <div className="blue-buy" id="buy">
        <button @click="addToCart(item)">
            buy for {{ prices[item] }}
        </button>
      <el-row class="mb-4">
        <el-button>Default</el-button>
        <el-button type="primary">Primary</el-button>
        <el-button type="success">Success</el-button>
        <el-button type="info">Info</el-button>
        <el-button type="warning">Warning</el-button>
        <el-button type="danger">Danger</el-button>
      </el-row>
    </div>
</template>
```
出现现象
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/13497831/216210451-2e3a5b1f-fd4f-4b29-a936-53f20eed7fe5.png">
子工程本地启动后，按钮元素存在，但是其中的文案等内容不存在。

**Comment by flyfishzy** [comment]
第一个问题，请尝试最新版本，应该已经解决的。
第二个问题，似乎与federation无关，可能是样式冲突了。

**Comment by imleeou** [comment]
> ### Versions
> * vite-plugin-federation: 1.1.14
> * vite: 4.0.3
> 
> 使用的是官方代码中vue3-advanced-demo工程
> 
> 出现的现象：
> 
> ## 第一个问题
> 未进行任何代码修改，安装依赖之后 本地工程启动之后 <img alt="image" width="1023" src="https://user-images.githubusercontent.com/13497831/216210080-73e763cd-8193-4294-8e90-36368d99845d.png">
> 
> 点击按钮之后上方未变色；
> 
> ## 第二个问题：就是在子工程team-blue中远程组件中添加element-plus组件
> 随便在buy中添加button组件
> 
> ```
> <template>
>     <div className="blue-buy" id="buy">
>         <button @click="addToCart(item)">
>             buy for {{ prices[item] }}
>         </button>
>       <el-row class="mb-4">
>         <el-button>Default</el-button>
>         <el-button type="primary">Primary</el-button>
>         <el-button type="success">Success</el-button>
>         <el-button type="info">Info</el-button>
>         <el-button type="warning">Warning</el-button>
>         <el-button type="danger">Danger</el-button>
>       </el-row>
>     </div>
> </template>
> ```
> 
> 出现现象 <img alt="image" width="1059" src="https://user-images.githubusercontent.com/13497831/216210451-2e3a5b1f-fd4f-4b29-a936-53f20eed7fe5.png"> 子工程本地启动后，按钮元素存在，但是其中的文案等内容不存在。

第二个问题是如何解决的呢，如果在子工程也安装element-plus是可以正常渲染，但能否通过shared element-plus来实现呢
