### ISSUE TITLE
not work with vue3 composition api

### ISSUE THREAD

**Issue by doannucphys** [originjs/vite-plugin-federation#344]
### Versions

- vite-plugin-federation: 
- vite: 

### Reproduction
create remote component with composition api of vue3 using stetup() function with simple button co increase count number.  

when import that function in host app, everything is ok but when click on number, nothing happen. 

But if in remote component use Options API, with export default {data:{return ....}}, it work

### What is Expected?
click on button on host app, it work

**Comment by T0miii** [comment]
Hello, this is a known issue and its being worked on. You can downgrade to version 1.1.13 for the time being , and that should work as expected.

**Comment by doannucphys** [comment]
thank you, i found solution with current version is use mix of vue3 composition and options api in the same component and it work perfect,

**Comment by ruleeeer** [comment]
> thank you, i found solution with current version is use mix of vue3 composition and options api in the same component and it work perfect,

I released a new version 1.2.0, you can try the new version to see if the problem still exists

**Comment by doannucphys** [comment]
Hi ruleeeer, I just test and it work perfect. 
Event with setup mode of shared store
Thank you
