### ISSUE TITLE
Expand settings for full-fledged work with Nginx

### ISSUE THREAD

**Issue by seapp88** [originjs/vite-plugin-federation#380]
### Hello! Thanks for this plugin.

Our project has a very complex architecture, so we use NGINX during development. In this regard, there are problems with shared modules. They refer to the host and port of the vite development server. But I need to remap the host and port for my NGINX server.

## Example
vite.config.ts - host app
```ts
export default {
    plugins: [
        federation({
            name: 'host-app',
            remotes: {
                remote_app: "http://localhost:5001/remoteEntry.js",
            },
            shared: ['vue']
        })
    ],
    server: {
      port: 3001
    }
}
```

<img width="885" alt="SCR-20230326-qtf" src="https://user-images.githubusercontent.com/37223663/227778436-c4682407-8ad0-49a3-8f49-6011b63b919c.png">

This is standard behavior and everything is ok.
But I'm using NGINX and it listens on port 3000 and I need to redefine the host and port from where the shared module will be loaded.

I tried changing the origin server setting. But I'm getting the wrong URL.

```ts
export default {
    plugins: [
        federation({
            name: 'host-app',
            remotes: {
                remote_app: "http://localhost:5001/remoteEntry.js",
            },
            shared: ['vue']
        })
    ],
    server: {
      port: 3001,
      origin: 'http://localhost:3000',
    }
}
```

<img width="867" alt="SCR-20230326-r3d" src="https://user-images.githubusercontent.com/37223663/227779094-de38d83f-e43f-47ae-97e1-58c06ebb7a6f.png">

## Solution
Add the ability to specify the host and port on which the shared module will be loaded

For example:

```ts
export default {
    plugins: [
        federation({
            name: 'host-app',
            remotes: {
                remote_app: "http://localhost:5001/remoteEntry.js",
            },
            shared: {
                vue: {
                    orign: 'http://localhost:3000',
                }
            }
        })
    ],
    server: {
      port: 3001,
      origin: 'http://localhost:3000',
    }
}
```

Or

```ts
export default {
    plugins: [
        federation({
            name: 'host-app',
            orign: 'http://localhost:3000',
            remotes: {
                remote_app: "http://localhost:5001/remoteEntry.js",
            },
            shared: {
                vue: {
                    
                }
            }
        })
    ],
    server: {
      port: 3001,
      origin: 'http://localhost:3000',
    }
}
```

**Comment by ruleeeer** [comment]
According to the document of [vite](https://vitejs.dev/config/server-options.html#server-host), it seems that the plugin should not generate an error address like `http://localhost:3000:3001`. Your configuration is correct
``` js
export default {
    plugins: [
        federation({
            name: 'host-app',
            remotes: {
                remote_app: "http://localhost:5001/remoteEntry.js",
            },
            shared: ['vue']
        })
    ],
    server: {
      port: 3001,
      origin: 'http://localhost:3000',
    }
}
```
but there seems to be something wrong with the handling of the plugin.

**Comment by ruleeeer** [comment]
I will fix it with a PR. Theoretically, after configuring `server.origin`, `server.port` should not be used as a reference item.
