### ISSUE TITLE
[vite]: Rollup failed to resolve import "__federation_fn_satisfy" from "virtual:__federation_fn_import".

### ISSUE THREAD

**Issue by oychao** [originjs/vite-plugin-federation#408]
vite build error. error message:

```bash
[vite]: Rollup failed to resolve import "__federation_fn_satisfy" from "virtual:__federation_fn_import".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "__federation_fn_satisfy" from "virtual:__federation_fn_import".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///.../node_modules/vite/dist/node/chunks/dep-a178814b.js:46546:23)
    ...
```

### Versions

- vite-plugin-federation: 1.2.2
- vite: 4.3.3

### What is actually happening?

no idea what __federation_fn_satisfy is.

**Comment by oychao** [comment]
My project is a Vite + React + SSR project, I removed `@originjs/vite-plugin-federation` in SSR server side vite configuration, the problem is gone.

**Comment by cz1996** [comment]
> My project is a Vite + React + SSR project, I removed `@originjs/vite-plugin-federation` in SSR server side vite configuration, the problem is gone.

哈喽 这个咋解决的呀

**Comment by mannymu** [comment]
same

**Comment by badasukerubin** [comment]
> My project is a Vite + React + SSR project, I removed `@originjs/vite-plugin-federation` in SSR server side vite configuration, the problem is gone.

How did you achieve this @oychao?
I've tried adding `@originjs/vite-plugin-federation` and `__federation__` to `ssr.optimizeDeps.exclude` but it wasn't resolved.
