### ISSUE TITLE
Support static import

### ISSUE THREAD

**Issue by ygj6** [originjs/vite-plugin-federation#41]
当前只支持动态导入remote模块，静态导入会报错找不到模块。
Currently, the remote module can be dynamically imported. If the remote module is statically imported, an error message is displayed indicating that the module cannot be found.

https://github.com/module-federation/module-federation-examples/blob/2f0e58e1e2a36c4a04621dc7aaf71a7a4cf70f4d/shared-routes2/app1/src/App.js#L6

**Comment by ewertonviana1** [comment]
news?

**Comment by ruleeeer** [comment]
> news?

Currently more work is being done on compatibility with webpack, and this part of the refinement may drive static import

**Comment by ruleeeer** [comment]
Static import will be available in release 1.1.2

**Comment by ruleeeer** [comment]
Released in version 1.1.2
