### ISSUE TITLE
Cannot run host when remote is down

### ISSUE THREAD

**Issue by nvhungkt** [originjs/vite-plugin-federation#445]
### Versions

- vite-plugin-federation: v1.2.3
- vite: v4.3.9

### Reproduction

I clone react-vite example, then run host server without remote server.

The result is a blank page.

Even if I wrap the remote Component with dynamic import and Suspense with fallback, the result is still a blank page

### What is Expected?

The application can work independently even if any remote is down with a fallback, that's expected behavior from a MFE app.

### What is actually happening?

The application cannot work independently.

**Comment by elimenko** [comment]
Having the same issue, I get an error like 
```
Uncaught TypeError: Failed to fetch dynamically imported module: http://localhost:5003/assets/remoteEntry.js
```
And the whole host App crashes. Couldn't find a way to avoid it

**Comment by clabnet** [comment]
Same issue.

**Comment by nguyenbatranvan** [comment]
I used to have this problem, and this is how I solved it when the remote failed or failed to load:
-  `npm install react-error-boundary`
- In host app :
```
const AppRemote = loadable(() => import("remoteApp/AppRemote"), {
  fallback: <p>...</p>
})
or 
const AppRemote = React.lazy(() => import("remoteApp/AppRemote"))
```
then 
```
 <ErrorBoundary fallback={<p>App Remote Error</p>}>
     
              <AppRemote/>

</ErrorBoundary>
```

With the above usage, when the remote fails to load, `App Remote Error` will be uploaded to replace AppRemote. Your host project is still working normally

**Comment by nvhungkt** [comment]
Turns out that I implemented in a wrong way. I will close the issue.

**Comment by seantunwin** [comment]
> Turns out that I implemented in a wrong way. I will close the issue.

@nvhungkt Would it be possible to share your 'correct' implementation, or explain what was wrong initially and how you fixed it?

I am having the same issue when `remote` is down and attempting to resolve to a fallback.

**Comment by nvhungkt** [comment]
@seantunwin Here you are:
```
import React, { lazy } from "react";
import { Suspense } from "react";

const Button = lazy(() => import('shared/Button'));

export class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }
  static getDerivedStateFromError(error) {
    return { hasError: true };
  }

  render() {
    if (this.state.hasError) {
      return <h1>Some thing went wrong</h1>;
    }
    return this.props.children;
  }
}

export default function RemoteMFE() {
  return (
    <ErrorBoundary>
      <Suspense fallback='loading'>
        <Button />
      </Suspense>
    </ErrorBoundary>
  )
}
```
