### ISSUE TITLE
Vite preload polyfill breaks imports on NestJS side

### ISSUE THREAD

**Issue by nick4fake** [originjs/vite-plugin-federation#451]
Vite preload polyfill plugin injects top level import inside remoteEntrypoint.js and should be disabled on projects that use this module:
https://vitejs.dev/config/build-options.html#build-modulepreload

The error:
````
Uncaught SyntaxError: Cannot use import statement outside a module (at remoteEntry.js?1688407163760:1:1)
````

Additionally Vite should be configured to target which disables ESM.

Unfortunately I haven't found any other ways to use this library with NextJS host.

**Comment by IgorBolotnikovGH** [comment]
@nick4fake did you manage to fix this issue?

**Comment by Fredkr** [comment]
@nick4fake Im having the same issue, did you manage to find a workaround?
