### ISSUE TITLE
NX -  Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by nguyenbatranvan** [originjs/vite-plugin-federation#456]
### Versions

- vite-plugin-federation: 1.2.3
- vite: 4.3.9

### Reproduction

- Last week, I tried to apply the federation module with NX (monorepo), I encountered the following problem:
<img width="832" alt="image" src="https://github.com/originjs/vite-plugin-federation/assets/19392455/025ab36a-3eff-423d-a0eb-ca0a6688d446">

- The problem only occurs when i use any 3rd party library with external context wrapper (react-router-dom, mantine/core...). It took me a few days of work to find the cause, but everything didn't work. Give me a little hint, even a little

- **Note: This problem is only in development environment. When I run in production, everything goes well**

Github project link about my problem:
[https://github.com/nguyenbatranvan/nx-vite-federation.git](https://github.com/nguyenbatranvan/nx-vite-federation.git)

**Comment by nguyenbatranvan** [comment]
problem solved

**Comment by cropd** [comment]
how did you solve it?

**Comment by nguyenbatranvan** [comment]
> how did you solve it?
config  cacheDir at the same level as the project
![image](https://github.com/originjs/vite-plugin-federation/assets/19392455/30fb2591-f07a-4c9c-981e-ca44d5093d55)

**Comment by nguyenbatranvan** [comment]
I mean, this treatment only applies when I use it with NX (nwrl)
![image](https://github.com/originjs/vite-plugin-federation/assets/19392455/4938f9fd-3367-4f4e-a042-c4a4c9098b5b)

**Comment by nguyenbatranvan** [comment]
I have the update in the repo. How to run is detailed in the file README.MD
