### ISSUE TITLE
无法引入url png svg

### ISSUE THREAD

**Issue by 572031690** [originjs/vite-plugin-federation#457]
当我使用模块联邦打包时,所有外链的图片，svg都无法加载，因为她的路径始终是相对路径也就是如果我
remote端是localhost:5000，图片的路径在 localhost:5000/assets/test.png 
当我启动host端时，
host端是localhost:4999,当我引入组件时，组件内部含有url引入的png，其始终会引入相对路径也就是  /assets/test.png  这会导致她取图片是从 localhost:4999/assets/test.png 获取，但是事实是 localhost:5000/assets/test.png  下才是正确的图片路径
但是我发现外链的css没有此问题，因为css模块联邦有专门封装dynamicLoadingCss方法进行导入解决了路径问题，但是为什么png，svg等等url引入资源没有解决此问题呢？

**Comment by nguyenbatranvan** [comment]
use the same public folders, and the problem will be solved. I have written a plugin to help with this, you can try it:
[https://www.npmjs.com/package/vite-multiple-assets](https://www.npmjs.com/package/vite-multiple-assets)

**Comment by 572031690** [comment]
thanks i will try, May I contact you in the future

**Comment by 572031690** [comment]
这个是用在哪里 remote端 还是host 端 有模块联邦结合的用法样例吗

**Comment by nguyenbatranvan** [comment]
> 这个是用在哪里 remote端 还是host 端 有模块联邦结合的用法样例吗

you can share with `nx monorepo`, here is an example of how i share a shared folder:

[Check out my repo](https://github.com/nguyenbatranvan/nx-vite-federation)

**Comment by 572031690** [comment]
thanks for you

**Comment by 572031690** [comment]
我现在有另外一个问题了那就是

**Comment by 572031690** [comment]
GET http://0.0.0.0/vue3-common/static/js/__federation_shared_vue.js net::ERR_ABORTED 404 (Not Found) 就是我打包完后会显示报错获取不到这个

**Comment by ygj6** [comment]
Try this vite config, it works for me!
```js
experimental: {
  renderBuiltUrl(filename: string, { hostId, hostType, type }: { hostId: string, hostType: 'js' | 'css' | 'html', type: 'public' | 'asset' }) {
    if (type === 'public') {
      return 'https://www.domain.com/' + filename
    }
    else if (path.extname(hostId) === '.js') {
      return { runtime: `window.__assetsPath(${JSON.stringify(filename)})` }
    }
    else {
      return 'https://cdn.domain.com/assets/' + filename
    }
  }
}
```
