### ISSUE TITLE
Shared files are downloaded multiple times

### ISSUE THREAD

**Issue by nguyenbatranvan** [originjs/vite-plugin-federation#459]
### Versions

- vite-plugin-federation: 1.2.3
- vite: 4.3.9

### Steps to reproduce
When I use remote and host, the project runs in production mode the files `__federation_shared_react ` & `__federation_shared_react-dom` are loaded twice
<img width="1482" alt="image" src="https://github.com/originjs/vite-plugin-federation/assets/19392455/83bbcbb2-74b5-48ee-bb60-9392204df1e1">

### What is Expected?
The files `__federation_shared_react ` & `__federation_shared_react-dom` only be downloaded once

**Comment by wijionejs** [comment]
Hey, are you using zustand in your remote app?
Have you found a solution?

**Comment by wijionejs** [comment]
> > Hey, are you using zustand in your remote app? Have you found a solution?
> 
> what is the problem with your zustand?

@nguyenbatranvan I've created an [issue](https://github.com/originjs/vite-plugin-federation/issues/478). You can peruse it if you want.

**Comment by nguyenbatranvan** [comment]
> > > Hey, are you using zustand in your remote app? Have you found a solution?
> > 
> > 
> > what is the problem with your zustand?
> 
> @nguyenbatranvan I've created an [issue](https://github.com/originjs/vite-plugin-federation/issues/478). You can peruse it if you want.

I came up with a workaround with it

**Comment by AsuraKev** [comment]
is this issue fixed in v1.3.1 ?

**Comment by nguyenbatranvan** [comment]
I recently went back to try to find out why, and I was able to complete this problem
[My repo](https://github.com/nguyenbatranvan/nx-vite-federation)
![image](https://github.com/originjs/vite-plugin-federation/assets/19392455/ba58f24e-b360-4eb6-9cbc-0808cf19f882)

**Comment by nguyenbatranvan** [comment]
> resolved as a work around or a proper fix?

not sure!! Maybe good and suitable for my current project
