### ISSUE TITLE
Application referring to wrong asset url when trying to fetch the routes from a remote application

### ISSUE THREAD

**Issue by enzi077** [originjs/vite-plugin-federation#461]
### Discussed in https://github.com/originjs/vite-plugin-federation/discussions/460

<div type='discussions-op-text'>

<sup>Originally posted by **enzi077** July 14, 2023</sup>
I am facing an issue while accessing running two of my vite (@quasar/app-vite: ^1.0.0, vite version: 2.9.16, vite-plugin-federation: 1.2.2) applications. One application is hosted at http://localhost:8083 which has multiple pages and routes. And then there is another application hosted at http://localhost:8084, which uses the pages of localhost:8083 and just displays them as it is. Now the problem here is, the assets built under localhost:8083 (remote app) need to be accessible to localhost:8084 (host) as well. But in reality when I build the host application, the assets of the remote are not there. Due to which it throws an error, that the page wasn't found. Ref. below:

Img 1:
![image](https://github.com/originjs/vite-plugin-federation/assets/38394892/0fc9cf11-46cf-4a37-881c-2380c0715252)

Img 2:
![image](https://github.com/originjs/vite-plugin-federation/assets/38394892/23ec73f1-b8f7-40ec-8208-74e224cfe71d)

As you can observe, in the second image, the routes are present along with their component keys (generated using vite-plugin-pages). And these routes are then shared with the host from the remote. And when the host goes on to access them, it does so by prefixing localhost:8084 rather than 8083. (as visible in img 1). 

The amazing thing is, the page does load but local SCSS (stylings) are not being applied, that is something we don't want. And of course I want to get rid of these errors.

I have tried various plugins and configurations. Nothin seems to work. Would be a great help if anyone can help me out here. Since, it's an organization managed project, hence can't reveal details more than this. 

Also this is my first time posting a question in a forum. So pardon if I haven't followed any regulations.

Thanks!</div>

**Comment by mrvan2851** [comment]
try this option in vite.config.js in remote repo 
https://vitejs.dev/config/shared-options.html#base

**Comment by enzi077** [comment]
@mrvan2851 I have tried what you have mentioned and played around. But it doesn't work.

**Comment by artem-tarasenko** [comment]
Did you change the output folder for js files?
__federation_fn_import__.js must be in the same folder as other __federation_* files, you can use rollup output options to try and put that file in the correct location.

**Comment by enzi077** [comment]
@artem-tarasenko I actually figured out another way to resolve my issue. I wrote a small code snippet that would generate all my asset files within my mentioned directory. And those I then expose to be consumed in another application. It solved my problem.
