### ISSUE TITLE
Could not load virtual:__federation__

### ISSUE THREAD

**Issue by yves-v** [originjs/vite-plugin-federation#502]
### Versions

- vite-plugin-federation: v1.3.1 
- vite: v4.4.5 

### Reproduction

[Repro](https://github.com/yves-v/repro-virtual-federation)

### Steps to reproduce

```
yarn
cd ./packages/plugin1
yarn build
```

### What is Expected?

Trying out the new runtime remote functionality as demoed [here](https://github.com/originjs/vite-plugin-federation/blob/main/packages/examples/vue3-demo-esm/layout/src/main.js)

I'm trying to import some functions from the virtual federation module to setup some remotes at runtime

```
import {
  __federation_method_setRemote,
  __federation_method_getRemote,
  __federation_method_wrapDefault,
  // @ts-ignore
} from "virtual:__federation__";
```

While building I encounter the following error:
``` 
[vite:load-fallback] Could not load virtual:__federation__ (imported by src/Plugin1App.tsx): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00virtual:__federation__'
error during build:
TypeError [PLUGIN_ERROR]: Could not load virtual:__federation__ (imported by src/Plugin1App.tsx): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00virtual:__federation__'
    at open (node:internal/fs/promises:456:10)
    at Object.readFile (node:internal/fs/promises:820:20)
    at Object.load (file:///D:/_poc/repro-virtual-federation/node_modules/vite/dist/node/chunks/dep-df561101.js:47019:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/_poc/repro-virtual-federation/node_modules/rollup/dist/es/shared/node-entry.js:25439:28)
    at async file:///D:/_poc/repro-virtual-federation/node_modules/rollup/dist/es/shared/node-entry.js:24606:75
    at async Queue.work (file:///D:/_poc/repro-virtual-federation/node_modules/rollup/dist/es/shared/node-entry.js:25649:32)
```

This is a use case I'm trying to get to work because I don't know all the remotes up front. In other words I want to load the remotes dynamically and don't want to configure them in `vite.config.ts`.

related question: is it by any means possible to expose a function from the original package `@originjs/vite-plugin-federation` instead of needing to import a virtual module?

**Comment by narushvalentine** [comment]
I have the same issue

**Comment by maciej-baruch** [comment]
You should at least stub them in the remotes in federation config:
`remote_name: ''`
Let me know if this does the trick.

**Comment by yves-v** [comment]
Yes, that did the trick. Thanks!
