### ISSUE TITLE
Can not run examples/react-vite project

### ISSUE THREAD

**Issue by alvin0216** [originjs/vite-plugin-federation#511]
### Versions

- vite-plugin-federation: ^1.2.3
- "vite": "^4.0.5"

### Reproduction
pnpm install && pnpm run build && pnpm run serve:

![image](https://github.com/originjs/vite-plugin-federation/assets/34113677/68371f7f-c178-4a59-8dca-ba332bf5b1db)

error info: __federation_shared_react-dom-c0b5c364.js:338 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Uncaught Error: Minified React error #130;

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by ruleeeer** [comment]
Try upgrading to version 1.3.2
<img width="439" alt="image" src="https://github.com/originjs/vite-plugin-federation/assets/70385062/3733cec5-766c-41b9-9fe6-0e1467896640">

**Comment by lukyncze** [comment]
@ruleeeer Just FYI, Alvin has a problem with different example.

**Comment by MichalJana** [comment]
I have the same issue with newly created project

- vite: 4.4.5

**Comment by alvin0216** [comment]
hello @lukyncze 

Sure. I followed the tutorial
Run `pnpm install`, then `pnpm run build` and `pnpm run serve`.

**Comment by alvin0216** [comment]
Hello @lukyncze 

I ran the above script and it works, thank you

**Comment by lukyncze** [comment]
Nice! I assume, you can now close the issue :blush: cc @alvin0216
