### ISSUE TITLE
Can not run examples/react-in-vue project

### ISSUE THREAD

**Issue by lukyncze** [originjs/vite-plugin-federation#513]
### Versions

- vite-plugin-federation: ^1.3.2
- vite: ^4.0.5

### Reproduction

pnpm install && pnpm run build:

<details open>
<summary>Additional Details</summary>
<br>
~/Desktop/vite-plugin-federation/packages/examples/react-in-vue$ pn build

> react-in-vue@1.0.0 build /home/lusu/Desktop/vite-plugin-federation/packages/examples/react-in-vue
> pnpm  --parallel --filter "./**" build

Scope: 3 of 58 workspace projects
home build$ vite build
layout build$ vite build
home build: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
home build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
home build:       1357 │         let result = await callback({
home build:            ╵                            ^
home build:     at packageEntryFailure (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21837:11)
home build:     at resolvePackageEntry (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21834:5)
home build:     at tryNodeResolve (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21572:20)
home build:     at file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62039:40
home build:     at requestCallbacks.on-resolve (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:28)
home build:     at handleRequest (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:723:19)
home build:     at handleIncomingPacket (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:745:7)
home build:     at Socket.readFromStdout (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:673:7)
home build:     at Socket.emit (node:events:513:28)
home build:     at addChunk (node:internal/streams/readable:324:12)
home build:   This error came from the "onResolve" callback registered here:
home build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
home build:       1281 │       let promise = setup({
home build:            ╵                     ^
home build:     at setup (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62028:27)
home build:     at handlePlugins (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:21)
home build:     at buildOrServeImpl (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:970:5)
home build:     at Object.buildOrServe (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:776:5)
home build:     at /home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:2117:17
home build:     at new Promise (<anonymous>)
home build:     at Object.build (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:2116:14)
home build:     at build (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1963:51)
home build:     at bundleConfigFile (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:61992:26)
home build:   The plugin "externalize-deps" was triggered by this import
home build:     vite.config.ts:3:23:
home build:       3 │ import federation from '@originjs/vite-plugin-federation'
home build:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
home build: failed to load config from /home/lusu/Desktop/vite-plugin-federation/packages/examples/react-in-vue/home/vite.config.ts
home build: error during build:
home build: Error: Build failed with 1 error:
home build: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
home build:     at failureErrorWithLog (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1596:15)
home build:     at /home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1052:28
home build:     at runOnEndCallbacks (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1468:61)
home build:     at buildResponseToResult (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1050:7)
home build:     at /home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1162:14
home build:     at responseCallbacks.<computed> (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:697:9)
home build:     at handleIncomingPacket (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:752:9)
home build:     at Socket.readFromStdout (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:673:7)
home build:     at Socket.emit (node:events:513:28)
home build:     at addChunk (node:internal/streams/readable:324:12)
layout build: ✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
layout build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27:
layout build:       1357 │         let result = await callback({
layout build:            ╵                            ^
layout build:     at packageEntryFailure (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21837:11)
layout build:     at resolvePackageEntry (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21834:5)
layout build:     at tryNodeResolve (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:21572:20)
layout build:     at file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62039:40
layout build:     at requestCallbacks.on-resolve (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:28)
layout build:     at handleRequest (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:723:19)
layout build:     at handleIncomingPacket (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:745:7)
layout build:     at Socket.readFromStdout (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:673:7)
layout build:     at Socket.emit (node:events:513:28)
layout build:     at addChunk (node:internal/streams/readable:324:12)
layout build:   This error came from the "onResolve" callback registered here:
layout build:     ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:20:
layout build:       1281 │       let promise = setup({
layout build:            ╵                     ^
layout build:     at setup (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:62028:27)
layout build:     at handlePlugins (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1281:21)
layout build:     at buildOrServeImpl (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:970:5)
layout build:     at Object.buildOrServe (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:776:5)
layout build:     at /home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:2117:17
layout build:     at new Promise (<anonymous>)
layout build:     at Object.build (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:2116:14)
layout build:     at build (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1963:51)
layout build:     at bundleConfigFile (file:///home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/vite@4.0.5_@types+node@18.6.4/node_modules/vite/dist/node/chunks/dep-9cd3c8cb.js:61992:26)
layout build:   The plugin "externalize-deps" was triggered by this import
layout build:     vite.config.ts:3:23:
layout build:       3 │ import federation from '@originjs/vite-plugin-federation'
layout build:         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
layout build: failed to load config from /home/lusu/Desktop/vite-plugin-federation/packages/examples/react-in-vue/layout/vite.config.ts
layout build: error during build:
layout build: Error: Build failed with 1 error:
layout build: ../../../../node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1357:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@originjs/vite-plugin-federation". The package may have incorrect main/module/exports specified in its package.json.
layout build:     at failureErrorWithLog (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1596:15)
layout build:     at /home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1052:28
layout build:     at runOnEndCallbacks (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1468:61)
layout build:     at buildResponseToResult (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1050:7)
layout build:     at /home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:1162:14
layout build:     at responseCallbacks.<computed> (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:697:9)
layout build:     at handleIncomingPacket (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:752:9)
layout build:     at Socket.readFromStdout (/home/lusu/Desktop/vite-plugin-federation/node_modules/.pnpm/esbuild@0.16.13/node_modules/esbuild/lib/main.js:673:7)
layout build:     at Socket.emit (node:events:513:28)
layout build:     at addChunk (node:internal/streams/readable:324:12)
layout build: Failed
/home/lusu/Desktop/vite-plugin-federation/packages/examples/react-in-vue/layout:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @react-in-vue/layout@1.0.0 build: `vite build`
Exit status 1
home build: Failed
 ELIFECYCLE  Command failed with exit code 1.</details>

### Steps to reproduce
- pnpm install && pnpm run build

### What is Expected?
- project will be build successfully.

### What is actually happening?
- build fails with errors.

**Comment by ruleeeer** [comment]
I think you may not have built vite-plugin-federation first
```
cd vite-plugin-federation
pnpm build
cd packages/examples/...
...
```

**Comment by lukyncze** [comment]
@ruleeeer I have not, will try. Thanks!

**Comment by lukyncze** [comment]
Works, one more time thank you!
