### ISSUE TITLE
Dynamic Remotes with React

### ISSUE THREAD

**Issue by dk-v** [originjs/vite-plugin-federation#526]
### Versions

- vite-plugin-federation: 1.3.2
- vite: 4.4.9

### Reproduction
I am trying to get the dynamic remotes feature to work with React but so far I've been unsuccessful. It appears like the remote module is fetched successfully but when I try to render the remote an error occurs. I would appreciate if someone could point out if I am doing something wrong.

<details open>
<summary>Additional Details</summary>
<br>

Host `App.tsx`
```Javascript
function App() {
  const [count, setCount] = useState(0);

  const [DynamicRemote, setDynamicRemote] = useState<FunctionComponent>();
  useEffect(() => {
    __federation_method_setRemote("dyn", {
      url: () => Promise.resolve("http://localhost:4201/assets/remoteEntry.js"),
      format: "esm",
      from: "vite",
    });

    __federation_method_getRemote("dyn", "./DynamicApp")
      .then((moduleWrapped) => __federation_method_unwrapDefault(moduleWrapped))
      .then((module) => {
        setDynamicRemote(module);
      });
  }, []);

  if (DynamicRemote) {
    return (
      <>
        <h1>Test dynamic remotes</h1>
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <Suspense>
          <DynamicRemote />
        </Suspense>
      </>
    );
  } else {
    return <h1>Loading...</h1>;
  }
export default App;

```

Host `vite.config`
``` Javascript
export default defineConfig({
  plugins: [
    react(),
    federation({
      name: "shell",
      remotes: {
        dyn: "",
      },
      shared: ["react", "react-dom"],
    }),
  ],
  server: {
    port: 4200,
  },
  build: {
    target: "esnext",
    cssCodeSplit: false,
    minify: false,
    modulePreload: false,
  },
});
```

Remote `App.tsx`
```Javascript
function App() {
  return <button>Hello from the dynamic remote!</button>;
}

export default App;
```

Remote `vite.config`
```Javascript
export default defineConfig({
  plugins: [
    react(),
    federation({
      name: "dyn",
      filename: "remoteEntry.js",
      exposes: {
        "./DynamicApp": "./src/App",
      },
      shared: ["react", "react-dom"],
    }),
  ],
  server: {
    port: 4201,
  },
  build: {
    target: "esnext",
    cssCodeSplit: false,
    minify: false,
    modulePreload: false,
  },
});
```

</details>

### Steps to reproduce
1. Build the remote and start the remote. 
2. Start the Host and open Dev Tools.

### What is Expected?
The remote loads dynamically and can be rendered like normal.

### What is actually happening?
I am getting the following errors when trying to render the remote: 
![image](https://github.com/originjs/vite-plugin-federation/assets/63596756/9ac6c743-08ea-44ab-b57a-3325ac5e67f3)

**Comment by eduardklinger** [comment]
It's working for me.

Just set your state variable like this:

`setDynamicRemote(() => module);`

**Comment by dk-v** [comment]
Thanks, that worked for me. However, when I try to build the project and run it via `pn preview`, I get an error saying

**Comment by dk-v** [comment]
Thanks, that worked for me when I run the host with `pnpm dev`. However, when I try to build the host and run it via `pnpm preview` I get an error that the shareScope is not defined.
![grafik](https://github.com/originjs/vite-plugin-federation/assets/63596756/ee562002-b7a5-46ac-a0e0-3e7bc442afa4)

Do you have any suggestions how I could fix this error?

**Comment by dk-v** [comment]
Ok, I figured it out. My problem was that I left the remotes property completely empty. You have to at least put some sort of placeholder there. 
```Javascript
remotes: {
    placeholder: "",
}
````
