### ISSUE TITLE
shared module which export default function like dayjs will get error TypeError: xxx is not a function

### ISSUE THREAD

**Issue by unformalized** [originjs/vite-plugin-federation#537]
### Versions

- vite-plugin-federation: 1.3.2
- vite: 4.1.2

### Reproduction
none

### Steps to reproduce

remote side:
```javascript
// vite.config.ts
plugins: [
    federation({
      name: 'demo',
      filename: 'remoteEntry.js',
      remotes: {
        xx:  'xxx',
      },
      shared: {
        vue: {},
        dayjs: {},
      }
    }),
  ],

// index.vue
import dayjs from 'dayjs';

dayjs().format('YYYY-MM-DD');
```

### What is Expected?
work without problem in prod env

### What is actually happening?
Typed error: dayjs is not a function in prod env

**Comment by unformalized** [comment]
[fix pr](https://github.com/originjs/vite-plugin-federation/pull/538)

**Comment by bustEXZ** [comment]
Same issue with clsx. When this will be merged?

**Comment by linxianxi** [comment]
dayjs still have this bug
