### ISSUE TITLE
Virtual federation creates own wrapShareModule and not use the globalThis.__federation_shared__

### ISSUE THREAD

**Issue by bustEXZ** [originjs/vite-plugin-federation#543]
Its easy to access with globalThis.__federation_shared__.

Virtual generation creates own wrapShareModule, and use globalThis.federation_shared and its dependencies. And same dependencies loading multiple times

**Comment by olyadanilova** [comment]
In code its easy to use -> `globalThis.__federation_shared__`

**Comment by bustEXZ** [comment]
Its easy to access with `globalThis.__federation_shared__`.

But now i have new problem.

Virtual generation creates own wrapShareModule, and use globalThis.__federation_shared__ and its dependencies. And same dependencies loading multiple times

**Comment by bustEXZ** [comment]
i fixed that in file remote-production.ts

Add scoped constant

```
const shareScope = options.shareScope || "default";
```

And change wrapShareModule:

```javascript
function merge(obj1, obj2) {
  const mergedObj = Object.assign(obj1, obj2);
  for (const key of Object.keys(mergedObj)) {
    if (typeof mergedObj[key] === 'object' && typeof obj2[key] === 'object') {
      mergedObj[key] = merge(mergedObj[key], obj2[key]);
    }
  }
  return mergedObj;
}

const wrapShareModule = ${REMOTE_FROM_PARAMETER} => {
  return merge({
    ${getModuleMarker("shareScope")}
  }, (globalThis.__federation_shared__ || {})['${shareScope}'] || {});
}
```
