### ISSUE TITLE
Upgrade to vite 5.x

### ISSUE THREAD

**Issue by maxKimoby** [originjs/vite-plugin-federation#550]
Can this package be upgraded according to vite 5.x?

**Comment by bustEXZ** [comment]
i already use vite@5, works fine

**Comment by MrDeerly** [comment]
> i already use vite@5, works fine

I remember that it didn't work for some time.. after i tested it again it just worked, so i guess some other dependency for vite was causing issues.

@maxKimoby feel free to try again with v5

**Comment by flyfishzy** [comment]
Thanks for the feedback! I think we can upgrade the example project to vite 5.x when we have free time.
