### ISSUE TITLE
can it support css Sandbox ?

### ISSUE THREAD

**Issue by hewson99** [originjs/vite-plugin-federation#620]
### Versions

- vite-plugin-federation: 
- vite: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is Expected?
i don't want the sub app affected by the css in main app

**Comment by yousmellnice** [comment]
unsupported

**Comment by He110te4m** [comment]
maybe you can try unocss/tailwind/windi or iframe or wujie
