### ISSUE TITLE
Remote cannot provide a component based on element-plus to host in dev mode

### ISSUE THREAD

**Issue by Adolph-WSY** [originjs/vite-plugin-federation#85]
### Versions
- originjs/vite-plugin-federation: 
- node: 
- element-plus: 
- vue: 

### Reproduction
dev mode + vite + vue + element-plus

<details open>
<summary>Additional Details</summary>
<br>
`__x00__virtual:__federation__:17 GET http://localhost:5104/node_modules/.vite/element-plus.js?v=cc040915 net::ERR_ABORTED 404 (Not Found)

localhost/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5104/node_modules/.vite/element-plus.js?v=cc040915
Promise.catch (async)
`
</details>

### Steps to reproduce
1. Create a project that uses vite + vue + element-plus. Create a el-button as a component to host.
Host is only rendered
`<el-button></el-button>`
2. Use vite‘ dev mode to start the host service.
 
### What is Expected?
Host renders a correct ElButton component

### What is actually happening?
The Host does not use element-plus, so there is no corresponding element-plus dependency in the `node_modules/.vite` folder, and remote cannot call host's element-plus for rendering

**Comment by liwangyong** [comment]
> #86 fix the bug, close issue.

I still can't seem to do it

**Comment by liwangyong** [comment]
> 

How did you solve it
